import { Translations } from './types'

export const ar: Translations = {
  code: 'ar',
  name: 'العربية',
  ui: {
    header: {
      detailsToggle: '📊 التفاصيل',
      themeToggle: '🌓 المظهر',
      downloadJson: '📦 JSON',
      downloadText: '📄 TXT',
      languageLabel: 'اللغة'
    },
    summary: {
      ticketId: 'معرّف التذكرة',
      category: 'الفئة',
      opener: 'فتح بواسطة',
      closedBy: 'أغلق بواسطة',
      totalMessages: 'الرسائل',
      participants: 'المشاركون',
      attachmentsEmbeds: 'المرفقات / المضمّنة',
      duration: 'المدة'
    },
    participants: {
      title: 'المشاركون',
      users: 'المستخدمون ({count})',
      bots: 'الروبوتات ({count})',
      none: 'لا يوجد',
      staff: 'STAFF'
    },
    viewers: {
      title: 'من كان يستطيع رؤية هذه القناة',
      roles: 'الرتب ({count})',
      users: 'المستخدمون ({count})',
      bots: 'الروبوتات ({count})',
      none: 'لا يوجد'
    },
    reply: {
      label: 'رد → رسالة {id}',
      hoverTitle: 'انقر للانتقال إلى الرسالة الأصلية',
      notFound: 'الرسالة الأصلية غير موجودة'
    },
    reactions: {
      reactedBy: 'التفاعلات ({count})',
      overflow: '+{count} آخرون',
      noUsers: 'تعذر جمع معلومات التفاعل',
      noUsersTooltip: 'لا توجد معلومات'
    },
    modal: {
      close: 'إغلاق',
      id: 'المعرّف',
      joined: 'انضم في',
      roles: 'الرتب',
      permissions: 'الصلاحيات',
      unknown: 'غير معروف',
      noRoles: 'لا توجد رتب',
      noPermissions: 'لا توجد صلاحيات',
      bot: 'BOT',
      staff: 'STAFF'
    },
    contextMenu: {
      viewProfile: 'عرض الملف',
      copyUserId: 'نسخ معرّف المستخدم',
      copyUsername: 'نسخ اسم المستخدم',
      message: 'الرسالة',
      copyMessageId: 'نسخ معرّف الرسالة',
      copyMessageText: 'نسخ نص الرسالة',
      copyMessageLink: 'نسخ رابط الرسالة'
    },
    toast: { copied: 'تم النسخ' },
    messages: { edited: '(معدَّلة)', systemMessage: '(رسالة نظام type={type})' },
    footer: 'Generated by discord-ticket-transcript v{version} · {time}'
  },
  duration: { days: 'ي', hours: 'س', minutes: 'د', seconds: 'ث' },
  permissions: {
    CreateInstantInvite: 'إنشاء دعوة',
    KickMembers: 'طرد الأعضاء',
    BanMembers: 'حظر الأعضاء',
    Administrator: 'مدير',
    ManageChannels: 'إدارة القنوات',
    ManageGuild: 'إدارة الخادم',
    AddReactions: 'إضافة تفاعلات',
    ViewAuditLog: 'عرض سجل المراجعة',
    PrioritySpeaker: 'متحدث ذو أولوية',
    Stream: 'فيديو',
    ViewChannel: 'عرض القناة',
    SendMessages: 'إرسال رسائل',
    SendTTSMessages: 'إرسال رسائل TTS',
    ManageMessages: 'إدارة الرسائل',
    EmbedLinks: 'تضمين روابط',
    AttachFiles: 'إرفاق ملفات',
    ReadMessageHistory: 'قراءة سجل الرسائل',
    MentionEveryone: 'الإشارة إلى @everyone و @here وجميع الرتب',
    UseExternalEmojis: 'استخدام رموز تعبيرية خارجية',
    ViewGuildInsights: 'عرض إحصائيات الخادم',
    Connect: 'الاتصال',
    Speak: 'التحدث',
    MuteMembers: 'كتم الأعضاء',
    DeafenMembers: 'إصمات الأعضاء',
    MoveMembers: 'نقل الأعضاء',
    UseVAD: 'استخدام كشف الصوت',
    ChangeNickname: 'تغيير الاسم المستعار',
    ManageNicknames: 'إدارة الأسماء المستعارة',
    ManageRoles: 'إدارة الرتب',
    ManageWebhooks: 'إدارة Webhooks',
    ManageEmojisAndStickers: 'إدارة الرموز والملصقات',
    ManageGuildExpressions: 'إدارة التعابير',
    UseApplicationCommands: 'استخدام أوامر التطبيق',
    RequestToSpeak: 'طلب التحدث',
    ManageEvents: 'إدارة الفعاليات',
    ManageThreads: 'إدارة المواضيع',
    CreatePublicThreads: 'إنشاء مواضيع عامة',
    CreatePrivateThreads: 'إنشاء مواضيع خاصة',
    UseExternalStickers: 'استخدام ملصقات خارجية',
    SendMessagesInThreads: 'إرسال رسائل في المواضيع',
    UseEmbeddedActivities: 'استخدام الأنشطة',
    ModerateMembers: 'توقيت الأعضاء',
    ViewCreatorMonetizationAnalytics: 'عرض تحليلات المنشئ',
    UseSoundboard: 'استخدام لوحة الأصوات',
    UseExternalSounds: 'استخدام أصوات خارجية',
    SendVoiceMessages: 'إرسال رسائل صوتية',
    SendPolls: 'إنشاء استطلاعات',
    CreateEvents: 'إنشاء فعاليات',
    CreateGuildExpressions: 'إنشاء تعابير',
    UseExternalApps: 'استخدام تطبيقات خارجية'
  }
}
