import { Translations } from './types'

export const cs: Translations = {
  code: 'cs',
  name: 'Čeština',
  ui: {
    header: {
      detailsToggle: '📊 Detaily',
      themeToggle: '🌓 Motiv',
      downloadJson: '📦 JSON',
      downloadText: '📄 TXT',
      languageLabel: 'Jazyk'
    },
    summary: {
      ticketId: 'ID tiketu',
      category: 'Kategorie',
      opener: 'Otevřel',
      closedBy: 'Zavřel',
      totalMessages: 'Zprávy',
      participants: 'Účastníci',
      attachmentsEmbeds: 'Přílohy / Vložené',
      duration: 'Doba trvání'
    },
    participants: {
      title: 'Účastníci',
      users: 'Uživatelé ({count})',
      bots: 'Boti ({count})',
      none: 'Žádný',
      staff: 'STAFF'
    },
    viewers: {
      title: 'Kdo mohl vidět tento kanál',
      roles: 'Role ({count})',
      users: 'Uživatelé ({count})',
      bots: 'Boti ({count})',
      none: 'Žádný'
    },
    reply: {
      label: 'Odpověď → zpráva {id}',
      hoverTitle: 'Kliknutím přejdete na původní zprávu',
      notFound: 'Původní zpráva nenalezena'
    },
    reactions: {
      reactedBy: 'Reakce ({count})',
      overflow: '+{count} dalších',
      noUsers: 'Informace o reakcích nejsou dostupné',
      noUsersTooltip: 'Žádné informace'
    },
    modal: {
      close: 'Zavřít',
      id: 'ID',
      joined: 'Připojen',
      roles: 'Role',
      permissions: 'Oprávnění',
      unknown: 'Neznámý',
      noRoles: 'Žádné role',
      noPermissions: 'Žádná oprávnění',
      bot: 'BOT',
      staff: 'STAFF'
    },
    contextMenu: {
      viewProfile: 'Zobrazit profil',
      copyUserId: 'Kopírovat ID uživatele',
      copyUsername: 'Kopírovat jméno',
      message: 'Zpráva',
      copyMessageId: 'Kopírovat ID zprávy',
      copyMessageText: 'Kopírovat text zprávy',
      copyMessageLink: 'Kopírovat odkaz'
    },
    toast: { copied: 'Zkopírováno' },
    messages: { edited: '(upraveno)', systemMessage: '(systémová zpráva type={type})' },
    footer: 'Generated by discord-ticket-transcript v{version} · {time}'
  },
  duration: { days: 'd', hours: 'h', minutes: 'm', seconds: 's' },
  permissions: {
    CreateInstantInvite: 'Vytvořit pozvánku',
    KickMembers: 'Vyhodit členy',
    BanMembers: 'Zakázat členy',
    Administrator: 'Administrátor',
    ManageChannels: 'Spravovat kanály',
    ManageGuild: 'Spravovat server',
    AddReactions: 'Přidávat reakce',
    ViewAuditLog: 'Zobrazit audit',
    PrioritySpeaker: 'Prioritní mluvčí',
    Stream: 'Video',
    ViewChannel: 'Zobrazit kanál',
    SendMessages: 'Posílat zprávy',
    SendTTSMessages: 'Posílat TTS zprávy',
    ManageMessages: 'Spravovat zprávy',
    EmbedLinks: 'Vkládat odkazy',
    AttachFiles: 'Připojovat soubory',
    ReadMessageHistory: 'Číst historii',
    MentionEveryone: 'Zmiňovat @everyone, @here a všechny role',
    UseExternalEmojis: 'Používat externí emoji',
    ViewGuildInsights: 'Zobrazit statistiky serveru',
    Connect: 'Připojit',
    Speak: 'Mluvit',
    MuteMembers: 'Ztlumit členy',
    DeafenMembers: 'Ohlušit členy',
    MoveMembers: 'Přesouvat členy',
    UseVAD: 'Detekce hlasu',
    ChangeNickname: 'Změnit přezdívku',
    ManageNicknames: 'Spravovat přezdívky',
    ManageRoles: 'Spravovat role',
    ManageWebhooks: 'Spravovat webhooky',
    ManageEmojisAndStickers: 'Spravovat emoji a nálepky',
    ManageGuildExpressions: 'Spravovat výrazy',
    UseApplicationCommands: 'Používat aplikační příkazy',
    RequestToSpeak: 'Požádat o slovo',
    ManageEvents: 'Spravovat události',
    ManageThreads: 'Spravovat vlákna',
    CreatePublicThreads: 'Vytvářet veřejná vlákna',
    CreatePrivateThreads: 'Vytvářet soukromá vlákna',
    UseExternalStickers: 'Používat externí nálepky',
    SendMessagesInThreads: 'Posílat zprávy ve vláknech',
    UseEmbeddedActivities: 'Používat aktivity',
    ModerateMembers: 'Timeout členů',
    ViewCreatorMonetizationAnalytics: 'Analytika tvůrců',
    UseSoundboard: 'Zvuková tabule',
    UseExternalSounds: 'Externí zvuky',
    SendVoiceMessages: 'Hlasové zprávy',
    SendPolls: 'Vytvářet ankety',
    CreateEvents: 'Vytvářet události',
    CreateGuildExpressions: 'Vytvářet výrazy',
    UseExternalApps: 'Externí aplikace'
  }
}
