import { Translations } from './types'

export const de: Translations = {
  code: 'de',
  name: 'Deutsch',
  ui: {
    header: {
      detailsToggle: '📊 Details',
      themeToggle: '🌓 Design',
      downloadJson: '📦 JSON',
      downloadText: '📄 TXT',
      languageLabel: 'Sprache'
    },
    summary: {
      ticketId: 'Ticket-ID',
      category: 'Kategorie',
      opener: 'Eröffnet von',
      closedBy: 'Geschlossen von',
      totalMessages: 'Nachrichten',
      participants: 'Teilnehmer',
      attachmentsEmbeds: 'Anhänge / Einbettungen',
      duration: 'Dauer'
    },
    participants: {
      title: 'Teilnehmer',
      users: 'Nutzer ({count})',
      bots: 'Bots ({count})',
      none: 'Keine',
      staff: 'STAFF'
    },
    viewers: {
      title: 'Wer konnte diesen Kanal sehen',
      roles: 'Rollen ({count})',
      users: 'Nutzer ({count})',
      bots: 'Bots ({count})',
      none: 'Keine'
    },
    reply: {
      label: 'Antwort → Nachricht {id}',
      hoverTitle: 'Klicken, um zur Originalnachricht zu springen',
      notFound: 'Originalnachricht nicht gefunden'
    },
    reactions: {
      reactedBy: 'Reagiert ({count})',
      overflow: '+{count} weitere',
      noUsers: 'Reaktionsdaten nicht erfasst',
      noUsersTooltip: 'Keine Reaktionsdaten'
    },
    modal: {
      close: 'Schließen',
      id: 'ID',
      joined: 'Beigetreten',
      roles: 'Rollen',
      permissions: 'Berechtigungen',
      unknown: 'Unbekannt',
      noRoles: 'Keine Rollen',
      noPermissions: 'Keine Berechtigungen',
      bot: 'BOT',
      staff: 'STAFF'
    },
    contextMenu: {
      viewProfile: 'Profil anzeigen',
      copyUserId: 'Nutzer-ID kopieren',
      copyUsername: 'Nutzernamen kopieren',
      message: 'Nachricht',
      copyMessageId: 'Nachrichten-ID kopieren',
      copyMessageText: 'Nachrichtentext kopieren',
      copyMessageLink: 'Nachrichten-Link kopieren'
    },
    toast: { copied: 'Kopiert' },
    messages: { edited: '(bearbeitet)', systemMessage: '(Systemnachricht type={type})' },
    footer: 'Generated by discord-ticket-transcript v{version} · {time}'
  },
  duration: { days: 'T', hours: 'Std', minutes: 'Min', seconds: 'Sek' },
  permissions: {
    CreateInstantInvite: 'Einladung erstellen',
    KickMembers: 'Mitglieder kicken',
    BanMembers: 'Mitglieder bannen',
    Administrator: 'Administrator',
    ManageChannels: 'Kanäle verwalten',
    ManageGuild: 'Server verwalten',
    AddReactions: 'Reaktionen hinzufügen',
    ViewAuditLog: 'Audit-Log ansehen',
    PrioritySpeaker: 'Prioritätssprecher',
    Stream: 'Video',
    ViewChannel: 'Kanal sehen',
    SendMessages: 'Nachrichten senden',
    SendTTSMessages: 'TTS-Nachrichten senden',
    ManageMessages: 'Nachrichten verwalten',
    EmbedLinks: 'Links einbetten',
    AttachFiles: 'Dateien anhängen',
    ReadMessageHistory: 'Nachrichtenverlauf lesen',
    MentionEveryone: '@everyone, @here und alle Rollen erwähnen',
    UseExternalEmojis: 'Externe Emojis verwenden',
    ViewGuildInsights: 'Server-Insights sehen',
    Connect: 'Verbinden',
    Speak: 'Sprechen',
    MuteMembers: 'Mitglieder stummschalten',
    DeafenMembers: 'Mitglieder taub schalten',
    MoveMembers: 'Mitglieder verschieben',
    UseVAD: 'Sprachaktivität verwenden',
    ChangeNickname: 'Nickname ändern',
    ManageNicknames: 'Nicknames verwalten',
    ManageRoles: 'Rollen verwalten',
    ManageWebhooks: 'Webhooks verwalten',
    ManageEmojisAndStickers: 'Emojis und Sticker verwalten',
    ManageGuildExpressions: 'Ausdrücke verwalten',
    UseApplicationCommands: 'Anwendungsbefehle verwenden',
    RequestToSpeak: 'Sprachanfrage stellen',
    ManageEvents: 'Events verwalten',
    ManageThreads: 'Threads verwalten',
    CreatePublicThreads: 'Öffentliche Threads erstellen',
    CreatePrivateThreads: 'Private Threads erstellen',
    UseExternalStickers: 'Externe Sticker verwenden',
    SendMessagesInThreads: 'Nachrichten in Threads senden',
    UseEmbeddedActivities: 'Aktivitäten verwenden',
    ModerateMembers: 'Mitglieder in Timeout setzen',
    ViewCreatorMonetizationAnalytics: 'Creator-Monetarisierung ansehen',
    UseSoundboard: 'Soundboard verwenden',
    UseExternalSounds: 'Externe Sounds verwenden',
    SendVoiceMessages: 'Sprachnachrichten senden',
    SendPolls: 'Umfragen erstellen',
    CreateEvents: 'Events erstellen',
    CreateGuildExpressions: 'Ausdrücke erstellen',
    UseExternalApps: 'Externe Apps verwenden'
  }
}
