import { Translations } from './types'

export const el: Translations = {
  code: 'el',
  name: 'Ελληνικά',
  ui: {
    header: {
      detailsToggle: '📊 Λεπτομέρειες',
      themeToggle: '🌓 Θέμα',
      downloadJson: '📦 JSON',
      downloadText: '📄 TXT',
      languageLabel: 'Γλώσσα'
    },
    summary: {
      ticketId: 'ID εισιτηρίου',
      category: 'Κατηγορία',
      opener: 'Άνοιξε',
      closedBy: 'Έκλεισε',
      totalMessages: 'Μηνύματα',
      participants: 'Συμμετέχοντες',
      attachmentsEmbeds: 'Συνημμένα / Ενσωματωμένα',
      duration: 'Διάρκεια'
    },
    participants: {
      title: 'Συμμετέχοντες',
      users: 'Χρήστες ({count})',
      bots: 'Bot ({count})',
      none: 'Κανένας',
      staff: 'STAFF'
    },
    viewers: {
      title: 'Ποιοι μπορούσαν να δουν αυτό το κανάλι',
      roles: 'Ρόλοι ({count})',
      users: 'Χρήστες ({count})',
      bots: 'Bot ({count})',
      none: 'Κανένας'
    },
    reply: {
      label: 'Απάντηση → μήνυμα {id}',
      hoverTitle: 'Κάντε κλικ για μετάβαση στο αρχικό μήνυμα',
      notFound: 'Το αρχικό μήνυμα δεν βρέθηκε'
    },
    reactions: {
      reactedBy: 'Αντιδράσεις ({count})',
      overflow: '+{count} ακόμη',
      noUsers: 'Δεν υπάρχουν δεδομένα αντιδράσεων',
      noUsersTooltip: 'Δεν υπάρχουν πληροφορίες'
    },
    modal: {
      close: 'Κλείσιμο',
      id: 'ID',
      joined: 'Συνδέθηκε',
      roles: 'Ρόλοι',
      permissions: 'Δικαιώματα',
      unknown: 'Άγνωστο',
      noRoles: 'Χωρίς ρόλους',
      noPermissions: 'Χωρίς δικαιώματα',
      bot: 'BOT',
      staff: 'STAFF'
    },
    contextMenu: {
      viewProfile: 'Προβολή προφίλ',
      copyUserId: 'Αντιγραφή ID χρήστη',
      copyUsername: 'Αντιγραφή ονόματος',
      message: 'Μήνυμα',
      copyMessageId: 'Αντιγραφή ID μηνύματος',
      copyMessageText: 'Αντιγραφή κειμένου',
      copyMessageLink: 'Αντιγραφή συνδέσμου'
    },
    toast: { copied: 'Αντιγράφηκε' },
    messages: { edited: '(επεξεργασμένο)', systemMessage: '(μήνυμα συστήματος type={type})' },
    footer: 'Generated by discord-ticket-transcript v{version} · {time}'
  },
  duration: { days: 'η', hours: 'ώ', minutes: 'λ', seconds: 'δ' },
  permissions: {
    CreateInstantInvite: 'Δημιουργία πρόσκλησης',
    KickMembers: 'Αποβολή μελών',
    BanMembers: 'Αποκλεισμός μελών',
    Administrator: 'Διαχειριστής',
    ManageChannels: 'Διαχείριση καναλιών',
    ManageGuild: 'Διαχείριση διακομιστή',
    AddReactions: 'Προσθήκη αντιδράσεων',
    ViewAuditLog: 'Προβολή αρχείου ελέγχου',
    PrioritySpeaker: 'Ομιλητής προτεραιότητας',
    Stream: 'Βίντεο',
    ViewChannel: 'Προβολή καναλιού',
    SendMessages: 'Αποστολή μηνυμάτων',
    SendTTSMessages: 'Αποστολή TTS',
    ManageMessages: 'Διαχείριση μηνυμάτων',
    EmbedLinks: 'Ενσωμάτωση συνδέσμων',
    AttachFiles: 'Επισύναψη αρχείων',
    ReadMessageHistory: 'Ανάγνωση ιστορικού',
    MentionEveryone: 'Αναφορά σε @everyone, @here και όλους τους ρόλους',
    UseExternalEmojis: 'Εξωτερικά emoji',
    ViewGuildInsights: 'Στατιστικά διακομιστή',
    Connect: 'Σύνδεση',
    Speak: 'Ομιλία',
    MuteMembers: 'Σίγαση μελών',
    DeafenMembers: 'Κώφωση μελών',
    MoveMembers: 'Μετακίνηση μελών',
    UseVAD: 'Ανίχνευση φωνής',
    ChangeNickname: 'Αλλαγή ψευδωνύμου',
    ManageNicknames: 'Διαχείριση ψευδωνύμων',
    ManageRoles: 'Διαχείριση ρόλων',
    ManageWebhooks: 'Διαχείριση webhook',
    ManageEmojisAndStickers: 'Διαχείριση emoji και αυτοκολλήτων',
    ManageGuildExpressions: 'Διαχείριση εκφράσεων',
    UseApplicationCommands: 'Εντολές εφαρμογής',
    RequestToSpeak: 'Αίτημα ομιλίας',
    ManageEvents: 'Διαχείριση εκδηλώσεων',
    ManageThreads: 'Διαχείριση νημάτων',
    CreatePublicThreads: 'Δημόσια νήματα',
    CreatePrivateThreads: 'Ιδιωτικά νήματα',
    UseExternalStickers: 'Εξωτερικά αυτοκόλλητα',
    SendMessagesInThreads: 'Μηνύματα σε νήματα',
    UseEmbeddedActivities: 'Δραστηριότητες',
    ModerateMembers: 'Timeout μελών',
    ViewCreatorMonetizationAnalytics: 'Ανάλυση δημιουργών',
    UseSoundboard: 'Πίνακας ήχων',
    UseExternalSounds: 'Εξωτερικοί ήχοι',
    SendVoiceMessages: 'Φωνητικά μηνύματα',
    SendPolls: 'Δημοσκοπήσεις',
    CreateEvents: 'Δημιουργία εκδηλώσεων',
    CreateGuildExpressions: 'Δημιουργία εκφράσεων',
    UseExternalApps: 'Εξωτερικές εφαρμογές'
  }
}
