import { Translations } from './types'

export const en: Translations = {
  code: 'en',
  name: 'English',
  ui: {
    header: {
      detailsToggle: '📊 Details',
      themeToggle: '🌓 Theme',
      downloadJson: '📦 JSON',
      downloadText: '📄 TXT',
      languageLabel: 'Language'
    },
    summary: {
      ticketId: 'Ticket ID',
      category: 'Category',
      opener: 'Opened by',
      closedBy: 'Closed by',
      totalMessages: 'Messages',
      participants: 'Participants',
      attachmentsEmbeds: 'Attachments / Embeds',
      duration: 'Duration'
    },
    participants: {
      title: 'Participants',
      users: 'Users ({count})',
      bots: 'Bots ({count})',
      none: 'None',
      staff: 'STAFF'
    },
    viewers: {
      title: 'Who could view this channel',
      roles: 'Roles ({count})',
      users: 'Users ({count})',
      bots: 'Bots ({count})',
      none: 'None'
    },
    reply: {
      label: 'Reply → message {id}',
      hoverTitle: 'Click to jump to the original message',
      notFound: 'Original message not found'
    },
    reactions: {
      reactedBy: 'Reacted ({count})',
      overflow: '+{count} more',
      noUsers: 'Reactor info not collected',
      noUsersTooltip: 'No reactor info'
    },
    modal: {
      close: 'Close',
      id: 'ID',
      joined: 'Joined',
      roles: 'Roles',
      permissions: 'Permissions',
      unknown: 'Unknown',
      noRoles: 'No role info',
      noPermissions: 'No permission info',
      bot: 'BOT',
      staff: 'STAFF'
    },
    contextMenu: {
      viewProfile: 'View profile',
      copyUserId: 'Copy user ID',
      copyUsername: 'Copy username',
      message: 'Message',
      copyMessageId: 'Copy message ID',
      copyMessageText: 'Copy message text',
      copyMessageLink: 'Copy message link'
    },
    toast: { copied: 'Copied' },
    messages: { edited: '(edited)', systemMessage: '(system message type={type})' },
    footer: 'Generated by discord-ticket-transcript v{version} · {time}'
  },
  duration: { days: 'd', hours: 'h', minutes: 'm', seconds: 's' },
  permissions: {
    CreateInstantInvite: 'Create Invite',
    KickMembers: 'Kick Members',
    BanMembers: 'Ban Members',
    Administrator: 'Administrator',
    ManageChannels: 'Manage Channels',
    ManageGuild: 'Manage Server',
    AddReactions: 'Add Reactions',
    ViewAuditLog: 'View Audit Log',
    PrioritySpeaker: 'Priority Speaker',
    Stream: 'Video',
    ViewChannel: 'View Channel',
    SendMessages: 'Send Messages',
    SendTTSMessages: 'Send TTS Messages',
    ManageMessages: 'Manage Messages',
    EmbedLinks: 'Embed Links',
    AttachFiles: 'Attach Files',
    ReadMessageHistory: 'Read Message History',
    MentionEveryone: 'Mention @everyone, @here, and All Roles',
    UseExternalEmojis: 'Use External Emoji',
    ViewGuildInsights: 'View Server Insights',
    Connect: 'Connect',
    Speak: 'Speak',
    MuteMembers: 'Mute Members',
    DeafenMembers: 'Deafen Members',
    MoveMembers: 'Move Members',
    UseVAD: 'Use Voice Activity',
    ChangeNickname: 'Change Nickname',
    ManageNicknames: 'Manage Nicknames',
    ManageRoles: 'Manage Roles',
    ManageWebhooks: 'Manage Webhooks',
    ManageEmojisAndStickers: 'Manage Emojis and Stickers',
    ManageGuildExpressions: 'Manage Expressions',
    UseApplicationCommands: 'Use Application Commands',
    RequestToSpeak: 'Request to Speak',
    ManageEvents: 'Manage Events',
    ManageThreads: 'Manage Threads',
    CreatePublicThreads: 'Create Public Threads',
    CreatePrivateThreads: 'Create Private Threads',
    UseExternalStickers: 'Use External Stickers',
    SendMessagesInThreads: 'Send Messages in Threads',
    UseEmbeddedActivities: 'Use Activities',
    ModerateMembers: 'Timeout Members',
    ViewCreatorMonetizationAnalytics: 'View Creator Monetization Analytics',
    UseSoundboard: 'Use Soundboard',
    UseExternalSounds: 'Use External Sounds',
    SendVoiceMessages: 'Send Voice Messages',
    SendPolls: 'Create Polls',
    CreateEvents: 'Create Events',
    CreateGuildExpressions: 'Create Expressions',
    UseExternalApps: 'Use External Apps'
  }
}
