import { Translations } from './types'

export const es: Translations = {
  code: 'es',
  name: 'Español',
  ui: {
    header: {
      detailsToggle: '📊 Detalles',
      themeToggle: '🌓 Tema',
      downloadJson: '📦 JSON',
      downloadText: '📄 TXT',
      languageLabel: 'Idioma'
    },
    summary: {
      ticketId: 'ID de ticket',
      category: 'Categoría',
      opener: 'Abierto por',
      closedBy: 'Cerrado por',
      totalMessages: 'Mensajes',
      participants: 'Participantes',
      attachmentsEmbeds: 'Adjuntos / Incrustados',
      duration: 'Duración'
    },
    participants: {
      title: 'Participantes',
      users: 'Usuarios ({count})',
      bots: 'Bots ({count})',
      none: 'Ninguno',
      staff: 'STAFF'
    },
    viewers: {
      title: 'Quiénes podían ver este canal',
      roles: 'Roles ({count})',
      users: 'Usuarios ({count})',
      bots: 'Bots ({count})',
      none: 'Ninguno'
    },
    reply: {
      label: 'Respuesta → mensaje {id}',
      hoverTitle: 'Haz clic para ir al mensaje original',
      notFound: 'Mensaje original no encontrado'
    },
    reactions: {
      reactedBy: 'Reaccionaron ({count})',
      overflow: '+{count} más',
      noUsers: 'No se pudo obtener la información de reacciones',
      noUsersTooltip: 'Sin información de reacciones'
    },
    modal: {
      close: 'Cerrar',
      id: 'ID',
      joined: 'Se unió',
      roles: 'Roles',
      permissions: 'Permisos',
      unknown: 'Desconocido',
      noRoles: 'Sin roles',
      noPermissions: 'Sin permisos',
      bot: 'BOT',
      staff: 'STAFF'
    },
    contextMenu: {
      viewProfile: 'Ver perfil',
      copyUserId: 'Copiar ID de usuario',
      copyUsername: 'Copiar nombre de usuario',
      message: 'Mensaje',
      copyMessageId: 'Copiar ID del mensaje',
      copyMessageText: 'Copiar texto del mensaje',
      copyMessageLink: 'Copiar enlace del mensaje'
    },
    toast: { copied: 'Copiado' },
    messages: { edited: '(editado)', systemMessage: '(mensaje del sistema type={type})' },
    footer: 'Generated by discord-ticket-transcript v{version} · {time}'
  },
  duration: { days: 'd', hours: 'h', minutes: 'm', seconds: 's' },
  permissions: {
    CreateInstantInvite: 'Crear invitación',
    KickMembers: 'Expulsar miembros',
    BanMembers: 'Banear miembros',
    Administrator: 'Administrador',
    ManageChannels: 'Gestionar canales',
    ManageGuild: 'Gestionar servidor',
    AddReactions: 'Añadir reacciones',
    ViewAuditLog: 'Ver registro de auditoría',
    PrioritySpeaker: 'Hablante prioritario',
    Stream: 'Vídeo',
    ViewChannel: 'Ver canal',
    SendMessages: 'Enviar mensajes',
    SendTTSMessages: 'Enviar mensajes TTS',
    ManageMessages: 'Gestionar mensajes',
    EmbedLinks: 'Insertar enlaces',
    AttachFiles: 'Adjuntar archivos',
    ReadMessageHistory: 'Leer historial de mensajes',
    MentionEveryone: 'Mencionar @everyone, @here y todos los roles',
    UseExternalEmojis: 'Usar emojis externos',
    ViewGuildInsights: 'Ver estadísticas del servidor',
    Connect: 'Conectar',
    Speak: 'Hablar',
    MuteMembers: 'Silenciar miembros',
    DeafenMembers: 'Ensordecer miembros',
    MoveMembers: 'Mover miembros',
    UseVAD: 'Usar detección de voz',
    ChangeNickname: 'Cambiar apodo',
    ManageNicknames: 'Gestionar apodos',
    ManageRoles: 'Gestionar roles',
    ManageWebhooks: 'Gestionar webhooks',
    ManageEmojisAndStickers: 'Gestionar emojis y stickers',
    ManageGuildExpressions: 'Gestionar expresiones',
    UseApplicationCommands: 'Usar comandos de aplicación',
    RequestToSpeak: 'Solicitar hablar',
    ManageEvents: 'Gestionar eventos',
    ManageThreads: 'Gestionar hilos',
    CreatePublicThreads: 'Crear hilos públicos',
    CreatePrivateThreads: 'Crear hilos privados',
    UseExternalStickers: 'Usar stickers externos',
    SendMessagesInThreads: 'Enviar mensajes en hilos',
    UseEmbeddedActivities: 'Usar actividades',
    ModerateMembers: 'Aislar miembros',
    ViewCreatorMonetizationAnalytics: 'Ver analíticas de monetización',
    UseSoundboard: 'Usar tablero de sonido',
    UseExternalSounds: 'Usar sonidos externos',
    SendVoiceMessages: 'Enviar mensajes de voz',
    SendPolls: 'Crear encuestas',
    CreateEvents: 'Crear eventos',
    CreateGuildExpressions: 'Crear expresiones',
    UseExternalApps: 'Usar apps externas'
  }
}
