import { Translations } from './types'

export const fi: Translations = {
  code: 'fi',
  name: 'Suomi',
  ui: {
    header: {
      detailsToggle: '📊 Tiedot',
      themeToggle: '🌓 Teema',
      downloadJson: '📦 JSON',
      downloadText: '📄 TXT',
      languageLabel: 'Kieli'
    },
    summary: {
      ticketId: 'Tiketin ID',
      category: 'Kategoria',
      opener: 'Avannut',
      closedBy: 'Sulkenut',
      totalMessages: 'Viestit',
      participants: 'Osallistujat',
      attachmentsEmbeds: 'Liitteet / Upotukset',
      duration: 'Kesto'
    },
    participants: {
      title: 'Osallistujat',
      users: 'Käyttäjät ({count})',
      bots: 'Botit ({count})',
      none: 'Ei mitään',
      staff: 'STAFF'
    },
    viewers: {
      title: 'Kuka saattoi nähdä tämän kanavan',
      roles: 'Roolit ({count})',
      users: 'Käyttäjät ({count})',
      bots: 'Botit ({count})',
      none: 'Ei mitään'
    },
    reply: {
      label: 'Vastaus → viesti {id}',
      hoverTitle: 'Siirry alkuperäiseen viestiin',
      notFound: 'Alkuperäistä viestiä ei löytynyt'
    },
    reactions: {
      reactedBy: 'Reaktiot ({count})',
      overflow: '+{count} lisää',
      noUsers: 'Reaktiotietoja ei saatu',
      noUsersTooltip: 'Ei tietoja'
    },
    modal: {
      close: 'Sulje',
      id: 'ID',
      joined: 'Liittyi',
      roles: 'Roolit',
      permissions: 'Oikeudet',
      unknown: 'Tuntematon',
      noRoles: 'Ei rooleja',
      noPermissions: 'Ei oikeuksia',
      bot: 'BOT',
      staff: 'STAFF'
    },
    contextMenu: {
      viewProfile: 'Näytä profiili',
      copyUserId: 'Kopioi käyttäjä-ID',
      copyUsername: 'Kopioi käyttäjänimi',
      message: 'Viesti',
      copyMessageId: 'Kopioi viesti-ID',
      copyMessageText: 'Kopioi viestin teksti',
      copyMessageLink: 'Kopioi viestin linkki'
    },
    toast: { copied: 'Kopioitu' },
    messages: { edited: '(muokattu)', systemMessage: '(järjestelmäviesti type={type})' },
    footer: 'Generated by discord-ticket-transcript v{version} · {time}'
  },
  duration: { days: 'pv', hours: 't', minutes: 'min', seconds: 's' },
  permissions: {
    CreateInstantInvite: 'Luo kutsu',
    KickMembers: 'Potki jäseniä',
    BanMembers: 'Porttikielto',
    Administrator: 'Ylläpitäjä',
    ManageChannels: 'Hallitse kanavia',
    ManageGuild: 'Hallitse palvelinta',
    AddReactions: 'Lisää reaktioita',
    ViewAuditLog: 'Näytä tarkastusloki',
    PrioritySpeaker: 'Etuoikeutettu puhuja',
    Stream: 'Video',
    ViewChannel: 'Näytä kanava',
    SendMessages: 'Lähetä viestejä',
    SendTTSMessages: 'Lähetä TTS-viestejä',
    ManageMessages: 'Hallitse viestejä',
    EmbedLinks: 'Upota linkkejä',
    AttachFiles: 'Liitä tiedostoja',
    ReadMessageHistory: 'Lue viestihistoria',
    MentionEveryone: 'Mainitse @everyone, @here ja kaikki roolit',
    UseExternalEmojis: 'Käytä ulkoisia emojeja',
    ViewGuildInsights: 'Palvelimen tilastot',
    Connect: 'Yhdistä',
    Speak: 'Puhu',
    MuteMembers: 'Mykistä jäsenet',
    DeafenMembers: 'Kuurosta jäsenet',
    MoveMembers: 'Siirrä jäseniä',
    UseVAD: 'Äänentunnistus',
    ChangeNickname: 'Vaihda kutsumanimi',
    ManageNicknames: 'Hallitse kutsumanimiä',
    ManageRoles: 'Hallitse rooleja',
    ManageWebhooks: 'Hallitse webhookkeja',
    ManageEmojisAndStickers: 'Hallitse emojeja ja tarroja',
    ManageGuildExpressions: 'Hallitse ilmaisuja',
    UseApplicationCommands: 'Käytä sovelluskomentoja',
    RequestToSpeak: 'Pyydä puheenvuoroa',
    ManageEvents: 'Hallitse tapahtumia',
    ManageThreads: 'Hallitse ketjuja',
    CreatePublicThreads: 'Luo julkisia ketjuja',
    CreatePrivateThreads: 'Luo yksityisiä ketjuja',
    UseExternalStickers: 'Käytä ulkoisia tarroja',
    SendMessagesInThreads: 'Lähetä viestejä ketjuissa',
    UseEmbeddedActivities: 'Käytä aktiviteetteja',
    ModerateMembers: 'Aikalisä jäsenille',
    ViewCreatorMonetizationAnalytics: 'Tekijöiden analyysit',
    UseSoundboard: 'Käytä äänitaulua',
    UseExternalSounds: 'Käytä ulkoisia ääniä',
    SendVoiceMessages: 'Lähetä ääniviestejä',
    SendPolls: 'Luo kyselyjä',
    CreateEvents: 'Luo tapahtumia',
    CreateGuildExpressions: 'Luo ilmaisuja',
    UseExternalApps: 'Käytä ulkoisia sovelluksia'
  }
}
