import { Translations } from './types'

export const fr: Translations = {
  code: 'fr',
  name: 'Français',
  ui: {
    header: {
      detailsToggle: '📊 Détails',
      themeToggle: '🌓 Thème',
      downloadJson: '📦 JSON',
      downloadText: '📄 TXT',
      languageLabel: 'Langue'
    },
    summary: {
      ticketId: 'ID du ticket',
      category: 'Catégorie',
      opener: 'Ouvert par',
      closedBy: 'Fermé par',
      totalMessages: 'Messages',
      participants: 'Participants',
      attachmentsEmbeds: 'Pièces jointes / Intégrations',
      duration: 'Durée'
    },
    participants: {
      title: 'Participants',
      users: 'Utilisateurs ({count})',
      bots: 'Bots ({count})',
      none: 'Aucun',
      staff: 'STAFF'
    },
    viewers: {
      title: 'Qui pouvait voir ce salon',
      roles: 'Rôles ({count})',
      users: 'Utilisateurs ({count})',
      bots: 'Bots ({count})',
      none: 'Aucun'
    },
    reply: {
      label: 'Réponse → message {id}',
      hoverTitle: 'Cliquez pour accéder au message original',
      notFound: 'Message original introuvable'
    },
    reactions: {
      reactedBy: 'Réactions ({count})',
      overflow: '+{count} de plus',
      noUsers: 'Informations de réaction non collectées',
      noUsersTooltip: 'Aucune information de réaction'
    },
    modal: {
      close: 'Fermer',
      id: 'ID',
      joined: 'A rejoint le',
      roles: 'Rôles',
      permissions: 'Permissions',
      unknown: 'Inconnu',
      noRoles: 'Aucun rôle',
      noPermissions: 'Aucune permission',
      bot: 'BOT',
      staff: 'STAFF'
    },
    contextMenu: {
      viewProfile: 'Voir le profil',
      copyUserId: "Copier l'ID utilisateur",
      copyUsername: "Copier le nom d'utilisateur",
      message: 'Message',
      copyMessageId: "Copier l'ID du message",
      copyMessageText: 'Copier le texte du message',
      copyMessageLink: 'Copier le lien du message'
    },
    toast: { copied: 'Copié' },
    messages: { edited: '(modifié)', systemMessage: '(message système type={type})' },
    footer: 'Generated by discord-ticket-transcript v{version} · {time}'
  },
  duration: { days: 'j', hours: 'h', minutes: 'min', seconds: 's' },
  permissions: {
    CreateInstantInvite: 'Créer une invitation',
    KickMembers: 'Expulser des membres',
    BanMembers: 'Bannir des membres',
    Administrator: 'Administrateur',
    ManageChannels: 'Gérer les salons',
    ManageGuild: 'Gérer le serveur',
    AddReactions: 'Ajouter des réactions',
    ViewAuditLog: "Voir le journal d'audit",
    PrioritySpeaker: 'Voix prioritaire',
    Stream: 'Vidéo',
    ViewChannel: 'Voir le salon',
    SendMessages: 'Envoyer des messages',
    SendTTSMessages: 'Envoyer des messages TTS',
    ManageMessages: 'Gérer les messages',
    EmbedLinks: 'Intégrer des liens',
    AttachFiles: 'Joindre des fichiers',
    ReadMessageHistory: "Lire l'historique des messages",
    MentionEveryone: 'Mentionner @everyone, @here et tous les rôles',
    UseExternalEmojis: 'Utiliser des emojis externes',
    ViewGuildInsights: 'Voir les statistiques du serveur',
    Connect: 'Se connecter',
    Speak: 'Parler',
    MuteMembers: 'Rendre muet',
    DeafenMembers: 'Rendre sourd',
    MoveMembers: 'Déplacer des membres',
    UseVAD: 'Utiliser la détection vocale',
    ChangeNickname: 'Changer de pseudo',
    ManageNicknames: 'Gérer les pseudos',
    ManageRoles: 'Gérer les rôles',
    ManageWebhooks: 'Gérer les webhooks',
    ManageEmojisAndStickers: 'Gérer les emojis et autocollants',
    ManageGuildExpressions: 'Gérer les expressions',
    UseApplicationCommands: "Utiliser les commandes d'application",
    RequestToSpeak: 'Demander la parole',
    ManageEvents: 'Gérer les événements',
    ManageThreads: 'Gérer les fils',
    CreatePublicThreads: 'Créer des fils publics',
    CreatePrivateThreads: 'Créer des fils privés',
    UseExternalStickers: 'Utiliser des autocollants externes',
    SendMessagesInThreads: 'Envoyer des messages dans les fils',
    UseEmbeddedActivities: 'Utiliser les activités',
    ModerateMembers: 'Exclure temporairement',
    ViewCreatorMonetizationAnalytics: 'Voir les analyses de monétisation',
    UseSoundboard: 'Utiliser le tableau de sons',
    UseExternalSounds: 'Utiliser des sons externes',
    SendVoiceMessages: 'Envoyer des messages vocaux',
    SendPolls: 'Créer des sondages',
    CreateEvents: 'Créer des événements',
    CreateGuildExpressions: 'Créer des expressions',
    UseExternalApps: 'Utiliser des applications externes'
  }
}
