import { Translations } from './types'

export const hi: Translations = {
  code: 'hi',
  name: 'हिन्दी',
  ui: {
    header: {
      detailsToggle: '📊 विवरण',
      themeToggle: '🌓 थीम',
      downloadJson: '📦 JSON',
      downloadText: '📄 TXT',
      languageLabel: 'भाषा'
    },
    summary: {
      ticketId: 'टिकट ID',
      category: 'श्रेणी',
      opener: 'खोला',
      closedBy: 'बंद किया',
      totalMessages: 'संदेश',
      participants: 'प्रतिभागी',
      attachmentsEmbeds: 'अटैचमेंट / एम्बेड',
      duration: 'अवधि'
    },
    participants: {
      title: 'प्रतिभागी',
      users: 'उपयोगकर्ता ({count})',
      bots: 'बॉट ({count})',
      none: 'कोई नहीं',
      staff: 'STAFF'
    },
    viewers: {
      title: 'इस चैनल को कौन देख सकता था',
      roles: 'भूमिकाएँ ({count})',
      users: 'उपयोगकर्ता ({count})',
      bots: 'बॉट ({count})',
      none: 'कोई नहीं'
    },
    reply: {
      label: 'उत्तर → संदेश {id}',
      hoverTitle: 'मूल संदेश पर जाने के लिए क्लिक करें',
      notFound: 'मूल संदेश नहीं मिला'
    },
    reactions: {
      reactedBy: 'प्रतिक्रियाएँ ({count})',
      overflow: '+{count} और',
      noUsers: 'प्रतिक्रिया डेटा उपलब्ध नहीं',
      noUsersTooltip: 'कोई जानकारी नहीं'
    },
    modal: {
      close: 'बंद करें',
      id: 'ID',
      joined: 'शामिल हुए',
      roles: 'भूमिकाएँ',
      permissions: 'अनुमतियाँ',
      unknown: 'अज्ञात',
      noRoles: 'कोई भूमिका नहीं',
      noPermissions: 'कोई अनुमति नहीं',
      bot: 'BOT',
      staff: 'STAFF'
    },
    contextMenu: {
      viewProfile: 'प्रोफ़ाइल देखें',
      copyUserId: 'उपयोगकर्ता ID कॉपी',
      copyUsername: 'उपयोगकर्ता नाम कॉपी',
      message: 'संदेश',
      copyMessageId: 'संदेश ID कॉपी',
      copyMessageText: 'संदेश पाठ कॉपी',
      copyMessageLink: 'संदेश लिंक कॉपी'
    },
    toast: { copied: 'कॉपी किया गया' },
    messages: { edited: '(संपादित)', systemMessage: '(सिस्टम संदेश type={type})' },
    footer: 'Generated by discord-ticket-transcript v{version} · {time}'
  },
  duration: { days: 'दि', hours: 'घं', minutes: 'मि', seconds: 'से' },
  permissions: {
    CreateInstantInvite: 'आमंत्रण बनाएँ',
    KickMembers: 'सदस्यों को निकालें',
    BanMembers: 'सदस्यों को प्रतिबंधित करें',
    Administrator: 'प्रशासक',
    ManageChannels: 'चैनल प्रबंधन',
    ManageGuild: 'सर्वर प्रबंधन',
    AddReactions: 'प्रतिक्रिया जोड़ें',
    ViewAuditLog: 'ऑडिट लॉग देखें',
    PrioritySpeaker: 'प्राथमिक वक्ता',
    Stream: 'वीडियो',
    ViewChannel: 'चैनल देखें',
    SendMessages: 'संदेश भेजें',
    SendTTSMessages: 'TTS संदेश भेजें',
    ManageMessages: 'संदेश प्रबंधन',
    EmbedLinks: 'लिंक एम्बेड करें',
    AttachFiles: 'फ़ाइलें संलग्न करें',
    ReadMessageHistory: 'संदेश इतिहास पढ़ें',
    MentionEveryone: '@everyone, @here और सभी भूमिकाओं का उल्लेख',
    UseExternalEmojis: 'बाहरी इमोजी का उपयोग',
    ViewGuildInsights: 'सर्वर इनसाइट्स देखें',
    Connect: 'कनेक्ट',
    Speak: 'बोलें',
    MuteMembers: 'सदस्यों को म्यूट करें',
    DeafenMembers: 'सदस्यों को डीफ़न करें',
    MoveMembers: 'सदस्यों को स्थानांतरित करें',
    UseVAD: 'वॉइस एक्टिविटी का उपयोग',
    ChangeNickname: 'उपनाम बदलें',
    ManageNicknames: 'उपनाम प्रबंधन',
    ManageRoles: 'भूमिका प्रबंधन',
    ManageWebhooks: 'Webhook प्रबंधन',
    ManageEmojisAndStickers: 'इमोजी और स्टिकर प्रबंधन',
    ManageGuildExpressions: 'अभिव्यक्ति प्रबंधन',
    UseApplicationCommands: 'एप्लिकेशन कमांड का उपयोग',
    RequestToSpeak: 'बोलने का अनुरोध',
    ManageEvents: 'इवेंट प्रबंधन',
    ManageThreads: 'थ्रेड प्रबंधन',
    CreatePublicThreads: 'सार्वजनिक थ्रेड बनाएँ',
    CreatePrivateThreads: 'निजी थ्रेड बनाएँ',
    UseExternalStickers: 'बाहरी स्टिकर का उपयोग',
    SendMessagesInThreads: 'थ्रेड में संदेश भेजें',
    UseEmbeddedActivities: 'गतिविधियों का उपयोग',
    ModerateMembers: 'सदस्यों को टाइमआउट',
    ViewCreatorMonetizationAnalytics: 'मॉनेटाइज़ेशन एनालिटिक्स',
    UseSoundboard: 'साउंडबोर्ड का उपयोग',
    UseExternalSounds: 'बाहरी ध्वनि का उपयोग',
    SendVoiceMessages: 'वॉइस संदेश भेजें',
    SendPolls: 'पोल बनाएँ',
    CreateEvents: 'इवेंट बनाएँ',
    CreateGuildExpressions: 'अभिव्यक्ति बनाएँ',
    UseExternalApps: 'बाहरी ऐप्स का उपयोग'
  }
}
