import { Translations } from './types'

export const id: Translations = {
  code: 'id',
  name: 'Bahasa Indonesia',
  ui: {
    header: {
      detailsToggle: '📊 Detail',
      themeToggle: '🌓 Tema',
      downloadJson: '📦 JSON',
      downloadText: '📄 TXT',
      languageLabel: 'Bahasa'
    },
    summary: {
      ticketId: 'ID tiket',
      category: 'Kategori',
      opener: 'Dibuka oleh',
      closedBy: 'Ditutup oleh',
      totalMessages: 'Pesan',
      participants: 'Peserta',
      attachmentsEmbeds: 'Lampiran / Tersemat',
      duration: 'Durasi'
    },
    participants: {
      title: 'Peserta',
      users: 'Pengguna ({count})',
      bots: 'Bot ({count})',
      none: 'Tidak ada',
      staff: 'STAFF'
    },
    viewers: {
      title: 'Siapa yang bisa melihat kanal ini',
      roles: 'Peran ({count})',
      users: 'Pengguna ({count})',
      bots: 'Bot ({count})',
      none: 'Tidak ada'
    },
    reply: {
      label: 'Balasan → pesan {id}',
      hoverTitle: 'Klik untuk pergi ke pesan asli',
      notFound: 'Pesan asli tidak ditemukan'
    },
    reactions: {
      reactedBy: 'Reaksi ({count})',
      overflow: '+{count} lainnya',
      noUsers: 'Informasi reaksi tidak tersedia',
      noUsersTooltip: 'Tidak ada info'
    },
    modal: {
      close: 'Tutup',
      id: 'ID',
      joined: 'Bergabung',
      roles: 'Peran',
      permissions: 'Izin',
      unknown: 'Tidak diketahui',
      noRoles: 'Tidak ada peran',
      noPermissions: 'Tidak ada izin',
      bot: 'BOT',
      staff: 'STAFF'
    },
    contextMenu: {
      viewProfile: 'Lihat profil',
      copyUserId: 'Salin ID pengguna',
      copyUsername: 'Salin nama pengguna',
      message: 'Pesan',
      copyMessageId: 'Salin ID pesan',
      copyMessageText: 'Salin teks pesan',
      copyMessageLink: 'Salin tautan pesan'
    },
    toast: { copied: 'Disalin' },
    messages: { edited: '(diedit)', systemMessage: '(pesan sistem type={type})' },
    footer: 'Generated by discord-ticket-transcript v{version} · {time}'
  },
  duration: { days: 'h', hours: 'j', minutes: 'm', seconds: 'd' },
  permissions: {
    CreateInstantInvite: 'Buat undangan',
    KickMembers: 'Keluarkan anggota',
    BanMembers: 'Blokir anggota',
    Administrator: 'Administrator',
    ManageChannels: 'Kelola kanal',
    ManageGuild: 'Kelola server',
    AddReactions: 'Tambah reaksi',
    ViewAuditLog: 'Lihat log audit',
    PrioritySpeaker: 'Pembicara prioritas',
    Stream: 'Video',
    ViewChannel: 'Lihat kanal',
    SendMessages: 'Kirim pesan',
    SendTTSMessages: 'Kirim pesan TTS',
    ManageMessages: 'Kelola pesan',
    EmbedLinks: 'Sematkan tautan',
    AttachFiles: 'Lampirkan file',
    ReadMessageHistory: 'Baca riwayat pesan',
    MentionEveryone: 'Sebut @everyone, @here, dan semua peran',
    UseExternalEmojis: 'Gunakan emoji eksternal',
    ViewGuildInsights: 'Lihat insight server',
    Connect: 'Hubungkan',
    Speak: 'Bicara',
    MuteMembers: 'Bisukan anggota',
    DeafenMembers: 'Tulikan anggota',
    MoveMembers: 'Pindahkan anggota',
    UseVAD: 'Gunakan deteksi suara',
    ChangeNickname: 'Ubah nama panggilan',
    ManageNicknames: 'Kelola nama panggilan',
    ManageRoles: 'Kelola peran',
    ManageWebhooks: 'Kelola webhook',
    ManageEmojisAndStickers: 'Kelola emoji dan stiker',
    ManageGuildExpressions: 'Kelola ekspresi',
    UseApplicationCommands: 'Gunakan perintah aplikasi',
    RequestToSpeak: 'Minta bicara',
    ManageEvents: 'Kelola acara',
    ManageThreads: 'Kelola utas',
    CreatePublicThreads: 'Buat utas publik',
    CreatePrivateThreads: 'Buat utas pribadi',
    UseExternalStickers: 'Gunakan stiker eksternal',
    SendMessagesInThreads: 'Kirim pesan di utas',
    UseEmbeddedActivities: 'Gunakan aktivitas',
    ModerateMembers: 'Timeout anggota',
    ViewCreatorMonetizationAnalytics: 'Lihat analitik kreator',
    UseSoundboard: 'Gunakan soundboard',
    UseExternalSounds: 'Gunakan suara eksternal',
    SendVoiceMessages: 'Kirim pesan suara',
    SendPolls: 'Buat polling',
    CreateEvents: 'Buat acara',
    CreateGuildExpressions: 'Buat ekspresi',
    UseExternalApps: 'Gunakan aplikasi eksternal'
  }
}
