import { Translations } from './types'

export const it: Translations = {
  code: 'it',
  name: 'Italiano',
  ui: {
    header: {
      detailsToggle: '📊 Dettagli',
      themeToggle: '🌓 Tema',
      downloadJson: '📦 JSON',
      downloadText: '📄 TXT',
      languageLabel: 'Lingua'
    },
    summary: {
      ticketId: 'ID ticket',
      category: 'Categoria',
      opener: 'Aperto da',
      closedBy: 'Chiuso da',
      totalMessages: 'Messaggi',
      participants: 'Partecipanti',
      attachmentsEmbeds: 'Allegati / Incorporati',
      duration: 'Durata'
    },
    participants: {
      title: 'Partecipanti',
      users: 'Utenti ({count})',
      bots: 'Bot ({count})',
      none: 'Nessuno',
      staff: 'STAFF'
    },
    viewers: {
      title: 'Chi poteva vedere questo canale',
      roles: 'Ruoli ({count})',
      users: 'Utenti ({count})',
      bots: 'Bot ({count})',
      none: 'Nessuno'
    },
    reply: {
      label: 'Risposta → messaggio {id}',
      hoverTitle: 'Fai clic per andare al messaggio originale',
      notFound: 'Messaggio originale non trovato'
    },
    reactions: {
      reactedBy: 'Reazioni ({count})',
      overflow: '+{count} altri',
      noUsers: 'Informazioni reazioni non raccolte',
      noUsersTooltip: 'Nessuna informazione sulle reazioni'
    },
    modal: {
      close: 'Chiudi',
      id: 'ID',
      joined: 'Iscritto il',
      roles: 'Ruoli',
      permissions: 'Permessi',
      unknown: 'Sconosciuto',
      noRoles: 'Nessun ruolo',
      noPermissions: 'Nessun permesso',
      bot: 'BOT',
      staff: 'STAFF'
    },
    contextMenu: {
      viewProfile: 'Vedi profilo',
      copyUserId: 'Copia ID utente',
      copyUsername: 'Copia nome utente',
      message: 'Messaggio',
      copyMessageId: 'Copia ID messaggio',
      copyMessageText: 'Copia testo messaggio',
      copyMessageLink: 'Copia link messaggio'
    },
    toast: { copied: 'Copiato' },
    messages: { edited: '(modificato)', systemMessage: '(messaggio di sistema type={type})' },
    footer: 'Generated by discord-ticket-transcript v{version} · {time}'
  },
  duration: { days: 'g', hours: 'h', minutes: 'min', seconds: 's' },
  permissions: {
    CreateInstantInvite: 'Crea invito',
    KickMembers: 'Espelli membri',
    BanMembers: 'Banna membri',
    Administrator: 'Amministratore',
    ManageChannels: 'Gestisci canali',
    ManageGuild: 'Gestisci server',
    AddReactions: 'Aggiungi reazioni',
    ViewAuditLog: 'Vedi registro di controllo',
    PrioritySpeaker: 'Oratore prioritario',
    Stream: 'Video',
    ViewChannel: 'Vedi canale',
    SendMessages: 'Invia messaggi',
    SendTTSMessages: 'Invia messaggi TTS',
    ManageMessages: 'Gestisci messaggi',
    EmbedLinks: 'Incorpora link',
    AttachFiles: 'Allega file',
    ReadMessageHistory: 'Leggi cronologia messaggi',
    MentionEveryone: 'Menziona @everyone, @here e tutti i ruoli',
    UseExternalEmojis: 'Usa emoji esterne',
    ViewGuildInsights: 'Vedi statistiche server',
    Connect: 'Connetti',
    Speak: 'Parla',
    MuteMembers: 'Silenzia membri',
    DeafenMembers: 'Rendi sordi',
    MoveMembers: 'Sposta membri',
    UseVAD: 'Usa rilevamento voce',
    ChangeNickname: 'Cambia soprannome',
    ManageNicknames: 'Gestisci soprannomi',
    ManageRoles: 'Gestisci ruoli',
    ManageWebhooks: 'Gestisci webhook',
    ManageEmojisAndStickers: 'Gestisci emoji e adesivi',
    ManageGuildExpressions: 'Gestisci espressioni',
    UseApplicationCommands: 'Usa comandi app',
    RequestToSpeak: 'Richiedi di parlare',
    ManageEvents: 'Gestisci eventi',
    ManageThreads: 'Gestisci discussioni',
    CreatePublicThreads: 'Crea discussioni pubbliche',
    CreatePrivateThreads: 'Crea discussioni private',
    UseExternalStickers: 'Usa adesivi esterni',
    SendMessagesInThreads: 'Invia messaggi nelle discussioni',
    UseEmbeddedActivities: 'Usa attività',
    ModerateMembers: 'Metti in timeout',
    ViewCreatorMonetizationAnalytics: 'Vedi analisi monetizzazione',
    UseSoundboard: 'Usa soundboard',
    UseExternalSounds: 'Usa suoni esterni',
    SendVoiceMessages: 'Invia messaggi vocali',
    SendPolls: 'Crea sondaggi',
    CreateEvents: 'Crea eventi',
    CreateGuildExpressions: 'Crea espressioni',
    UseExternalApps: 'Usa app esterne'
  }
}
