import { Translations } from './types'

export const ja: Translations = {
  code: 'ja',
  name: '日本語',
  ui: {
    header: {
      detailsToggle: '📊 詳細',
      themeToggle: '🌓 テーマ',
      downloadJson: '📦 JSON',
      downloadText: '📄 TXT',
      languageLabel: '言語'
    },
    summary: {
      ticketId: 'チケットID',
      category: 'カテゴリ',
      opener: '作成者',
      closedBy: '終了者',
      totalMessages: 'メッセージ数',
      participants: '参加者',
      attachmentsEmbeds: '添付 / 埋め込み',
      duration: '期間'
    },
    participants: {
      title: '参加者',
      users: 'ユーザー ({count})',
      bots: 'ボット ({count})',
      none: 'なし',
      staff: 'スタッフ'
    },
    viewers: {
      title: 'このチャンネルを閲覧できた対象',
      roles: 'ロール ({count})',
      users: 'ユーザー ({count})',
      bots: 'ボット ({count})',
      none: 'なし'
    },
    reply: {
      label: '返信 → メッセージ {id}',
      hoverTitle: 'クリックで元メッセージへ移動',
      notFound: '元のメッセージが見つかりません'
    },
    reactions: {
      reactedBy: 'リアクション ({count})',
      overflow: '他 {count}人',
      noUsers: 'リアクション情報が取得できませんでした',
      noUsersTooltip: 'リアクション情報なし'
    },
    modal: {
      close: '閉じる',
      id: 'ID',
      joined: '参加日',
      roles: 'ロール',
      permissions: '権限',
      unknown: '不明',
      noRoles: 'ロール情報なし',
      noPermissions: '権限情報なし',
      bot: 'BOT',
      staff: 'スタッフ'
    },
    contextMenu: {
      viewProfile: 'プロフィールを見る',
      copyUserId: 'ユーザーIDをコピー',
      copyUsername: 'ユーザー名をコピー',
      message: 'メッセージ',
      copyMessageId: 'メッセージIDをコピー',
      copyMessageText: 'メッセージ本文をコピー',
      copyMessageLink: 'メッセージリンクをコピー'
    },
    toast: { copied: 'コピーしました' },
    messages: { edited: '(編集済み)', systemMessage: '(システムメッセージ type={type})' },
    footer: 'Generated by discord-ticket-transcript v{version} · {time}'
  },
  duration: { days: '日', hours: '時間', minutes: '分', seconds: '秒' },
  permissions: {
    CreateInstantInvite: '招待を作成',
    KickMembers: 'メンバーをキック',
    BanMembers: 'メンバーをBAN',
    Administrator: '管理者',
    ManageChannels: 'チャンネルの管理',
    ManageGuild: 'サーバーの管理',
    AddReactions: 'リアクションの追加',
    ViewAuditLog: '監査ログの閲覧',
    PrioritySpeaker: '優先スピーカー',
    Stream: 'ビデオ',
    ViewChannel: 'チャンネルを見る',
    SendMessages: 'メッセージを送信',
    SendTTSMessages: 'TTSメッセージを送信',
    ManageMessages: 'メッセージの管理',
    EmbedLinks: '埋め込みリンク',
    AttachFiles: 'ファイルの添付',
    ReadMessageHistory: 'メッセージ履歴を読む',
    MentionEveryone: '@everyone、@here、全ロールにメンション',
    UseExternalEmojis: '外部の絵文字を使用',
    ViewGuildInsights: 'サーバーインサイトの閲覧',
    Connect: '接続',
    Speak: '発言',
    MuteMembers: 'メンバーをミュート',
    DeafenMembers: 'メンバーをスピーカーミュート',
    MoveMembers: 'メンバーを移動',
    UseVAD: '音声検出を使用',
    ChangeNickname: 'ニックネームの変更',
    ManageNicknames: 'ニックネームの管理',
    ManageRoles: 'ロールの管理',
    ManageWebhooks: 'ウェブフックの管理',
    ManageEmojisAndStickers: '絵文字とスタンプの管理',
    ManageGuildExpressions: '表現の管理',
    UseApplicationCommands: 'アプリコマンドの使用',
    RequestToSpeak: '発言をリクエスト',
    ManageEvents: 'イベントの管理',
    ManageThreads: 'スレッドの管理',
    CreatePublicThreads: '公開スレッドの作成',
    CreatePrivateThreads: 'プライベートスレッドの作成',
    UseExternalStickers: '外部スタンプの使用',
    SendMessagesInThreads: 'スレッドでメッセージを送信',
    UseEmbeddedActivities: 'アクティビティの使用',
    ModerateMembers: 'メンバーをタイムアウト',
    ViewCreatorMonetizationAnalytics: 'クリエイター収益分析の閲覧',
    UseSoundboard: 'サウンドボードの使用',
    UseExternalSounds: '外部サウンドの使用',
    SendVoiceMessages: '音声メッセージを送信',
    SendPolls: '投票を作成',
    CreateEvents: 'イベントの作成',
    CreateGuildExpressions: '表現の作成',
    UseExternalApps: '外部アプリの使用'
  }
}
