import { Translations } from './types'

export const ko: Translations = {
  code: 'ko',
  name: '한국어',
  ui: {
    header: {
      detailsToggle: '📊 상세 정보',
      themeToggle: '🌓 테마',
      downloadJson: '📦 JSON',
      downloadText: '📄 TXT',
      languageLabel: '언어'
    },
    summary: {
      ticketId: '티켓 ID',
      category: '카테고리',
      opener: '개설자',
      closedBy: '종료자',
      totalMessages: '총 메시지',
      participants: '참여자',
      attachmentsEmbeds: '첨부/임베드',
      duration: '지속 시간'
    },
    participants: {
      title: '참여자',
      users: '유저 ({count})',
      bots: '봇 ({count})',
      none: '없음',
      staff: 'STAFF'
    },
    viewers: {
      title: '이 채널을 열람할 수 있었던 대상',
      roles: '역할 ({count})',
      users: '유저 ({count})',
      bots: '봇 ({count})',
      none: '없음'
    },
    reply: {
      label: '답장 → 메시지 {id}',
      hoverTitle: '클릭하여 원본 메시지로 이동',
      notFound: '원본 메시지를 찾을 수 없습니다'
    },
    reactions: {
      reactedBy: '반응한 사람 ({count})',
      overflow: '외 {count}명',
      noUsers: '반응자 정보를 수집하지 못했습니다',
      noUsersTooltip: '반응자 정보 없음'
    },
    modal: {
      close: '닫기',
      id: 'ID',
      joined: '가입일',
      roles: '역할',
      permissions: '권한',
      unknown: '알 수 없음',
      noRoles: '역할 정보 없음',
      noPermissions: '권한 정보 없음',
      bot: 'BOT',
      staff: 'STAFF'
    },
    contextMenu: {
      viewProfile: '프로필 보기',
      copyUserId: '유저 ID 복사',
      copyUsername: '유저 이름 복사',
      message: '메시지',
      copyMessageId: '메시지 ID 복사',
      copyMessageText: '메시지 텍스트 복사',
      copyMessageLink: '메시지 링크 복사'
    },
    toast: { copied: '복사됨' },
    messages: { edited: '(편집됨)', systemMessage: '(시스템 메시지 type={type})' },
    footer: 'Generated by discord-ticket-transcript v{version} · {time}'
  },
  duration: { days: '일', hours: '시간', minutes: '분', seconds: '초' },
  permissions: {
    CreateInstantInvite: '초대 코드 만들기',
    KickMembers: '멤버 추방',
    BanMembers: '멤버 차단',
    Administrator: '관리자',
    ManageChannels: '채널 관리하기',
    ManageGuild: '서버 관리하기',
    AddReactions: '반응 추가하기',
    ViewAuditLog: '감사 로그 보기',
    PrioritySpeaker: '우선 발언권',
    Stream: '비디오',
    ViewChannel: '채널 보기',
    SendMessages: '메시지 보내기',
    SendTTSMessages: 'TTS 메시지 보내기',
    ManageMessages: '메시지 관리',
    EmbedLinks: '링크 첨부',
    AttachFiles: '파일 첨부',
    ReadMessageHistory: '지난 메시지 읽기',
    MentionEveryone: '@everyone, @here, 모든 역할 멘션',
    UseExternalEmojis: '외부 이모티콘 사용',
    ViewGuildInsights: '서버 인사이트 보기',
    Connect: '연결',
    Speak: '말하기',
    MuteMembers: '멤버 마이크 음소거',
    DeafenMembers: '멤버 헤드셋 음소거',
    MoveMembers: '멤버 이동하기',
    UseVAD: '음성 감지 사용',
    ChangeNickname: '별명 변경',
    ManageNicknames: '별명 관리',
    ManageRoles: '역할 관리',
    ManageWebhooks: '웹후크 관리',
    ManageEmojisAndStickers: '이모지 및 스티커 관리',
    ManageGuildExpressions: '이모지 및 스티커 관리',
    UseApplicationCommands: '애플리케이션 명령어 사용',
    RequestToSpeak: '발언권 요청',
    ManageEvents: '이벤트 관리',
    ManageThreads: '스레드 관리',
    CreatePublicThreads: '공개 스레드 만들기',
    CreatePrivateThreads: '비공개 스레드 만들기',
    UseExternalStickers: '외부 스티커 사용',
    SendMessagesInThreads: '스레드에서 메시지 보내기',
    UseEmbeddedActivities: '액티비티 사용',
    ModerateMembers: '멤버 타임아웃',
    ViewCreatorMonetizationAnalytics: '크리에이터 수익 분석 보기',
    UseSoundboard: '사운드보드 사용',
    UseExternalSounds: '외부 사운드 사용',
    SendVoiceMessages: '음성 메시지 보내기',
    SendPolls: '투표 만들기',
    CreateEvents: '이벤트 만들기',
    CreateGuildExpressions: '이모지/스티커/사운드 만들기',
    UseExternalApps: '외부 앱 사용'
  }
}
