import { Translations } from './types'

export const nl: Translations = {
  code: 'nl',
  name: 'Nederlands',
  ui: {
    header: {
      detailsToggle: '📊 Details',
      themeToggle: '🌓 Thema',
      downloadJson: '📦 JSON',
      downloadText: '📄 TXT',
      languageLabel: 'Taal'
    },
    summary: {
      ticketId: 'Ticket-ID',
      category: 'Categorie',
      opener: 'Geopend door',
      closedBy: 'Gesloten door',
      totalMessages: 'Berichten',
      participants: 'Deelnemers',
      attachmentsEmbeds: 'Bijlagen / Embeds',
      duration: 'Duur'
    },
    participants: {
      title: 'Deelnemers',
      users: 'Gebruikers ({count})',
      bots: 'Bots ({count})',
      none: 'Geen',
      staff: 'STAFF'
    },
    viewers: {
      title: 'Wie dit kanaal kon zien',
      roles: 'Rollen ({count})',
      users: 'Gebruikers ({count})',
      bots: 'Bots ({count})',
      none: 'Geen'
    },
    reply: {
      label: 'Antwoord → bericht {id}',
      hoverTitle: 'Klik om naar het originele bericht te gaan',
      notFound: 'Origineel bericht niet gevonden'
    },
    reactions: {
      reactedBy: 'Gereageerd ({count})',
      overflow: '+{count} meer',
      noUsers: 'Reactiegegevens niet verzameld',
      noUsersTooltip: 'Geen reactiegegevens'
    },
    modal: {
      close: 'Sluiten',
      id: 'ID',
      joined: 'Lid geworden',
      roles: 'Rollen',
      permissions: 'Rechten',
      unknown: 'Onbekend',
      noRoles: 'Geen rollen',
      noPermissions: 'Geen rechten',
      bot: 'BOT',
      staff: 'STAFF'
    },
    contextMenu: {
      viewProfile: 'Profiel bekijken',
      copyUserId: 'Gebruikers-ID kopiëren',
      copyUsername: 'Gebruikersnaam kopiëren',
      message: 'Bericht',
      copyMessageId: 'Bericht-ID kopiëren',
      copyMessageText: 'Berichttekst kopiëren',
      copyMessageLink: 'Berichtlink kopiëren'
    },
    toast: { copied: 'Gekopieerd' },
    messages: { edited: '(bewerkt)', systemMessage: '(systeembericht type={type})' },
    footer: 'Generated by discord-ticket-transcript v{version} · {time}'
  },
  duration: { days: 'd', hours: 'u', minutes: 'min', seconds: 's' },
  permissions: {
    CreateInstantInvite: 'Uitnodiging maken',
    KickMembers: 'Leden kicken',
    BanMembers: 'Leden bannen',
    Administrator: 'Beheerder',
    ManageChannels: 'Kanalen beheren',
    ManageGuild: 'Server beheren',
    AddReactions: 'Reacties toevoegen',
    ViewAuditLog: 'Auditlog bekijken',
    PrioritySpeaker: 'Prioriteitsspreker',
    Stream: 'Video',
    ViewChannel: 'Kanaal bekijken',
    SendMessages: 'Berichten verzenden',
    SendTTSMessages: 'TTS-berichten verzenden',
    ManageMessages: 'Berichten beheren',
    EmbedLinks: 'Links insluiten',
    AttachFiles: 'Bestanden toevoegen',
    ReadMessageHistory: 'Berichtgeschiedenis lezen',
    MentionEveryone: '@everyone, @here en alle rollen vermelden',
    UseExternalEmojis: 'Externe emojis gebruiken',
    ViewGuildInsights: 'Serverinzichten bekijken',
    Connect: 'Verbinden',
    Speak: 'Spreken',
    MuteMembers: 'Leden dempen',
    DeafenMembers: 'Leden doof maken',
    MoveMembers: 'Leden verplaatsen',
    UseVAD: 'Spraakdetectie gebruiken',
    ChangeNickname: 'Bijnaam wijzigen',
    ManageNicknames: 'Bijnamen beheren',
    ManageRoles: 'Rollen beheren',
    ManageWebhooks: 'Webhooks beheren',
    ManageEmojisAndStickers: 'Emojis en stickers beheren',
    ManageGuildExpressions: 'Expressies beheren',
    UseApplicationCommands: 'Applicatieopdrachten gebruiken',
    RequestToSpeak: 'Spreekverzoek',
    ManageEvents: 'Evenementen beheren',
    ManageThreads: 'Threads beheren',
    CreatePublicThreads: 'Openbare threads maken',
    CreatePrivateThreads: 'Privéthreads maken',
    UseExternalStickers: 'Externe stickers gebruiken',
    SendMessagesInThreads: 'Berichten in threads verzenden',
    UseEmbeddedActivities: 'Activiteiten gebruiken',
    ModerateMembers: 'Leden time-out geven',
    ViewCreatorMonetizationAnalytics: 'Monetisatie-analyses bekijken',
    UseSoundboard: 'Geluidsbord gebruiken',
    UseExternalSounds: 'Externe geluiden gebruiken',
    SendVoiceMessages: 'Spraakberichten verzenden',
    SendPolls: "Polls maken",
    CreateEvents: 'Evenementen maken',
    CreateGuildExpressions: 'Expressies maken',
    UseExternalApps: 'Externe apps gebruiken'
  }
}
