import { Translations } from './types'

export const pl: Translations = {
  code: 'pl',
  name: 'Polski',
  ui: {
    header: {
      detailsToggle: '📊 Szczegóły',
      themeToggle: '🌓 Motyw',
      downloadJson: '📦 JSON',
      downloadText: '📄 TXT',
      languageLabel: 'Język'
    },
    summary: {
      ticketId: 'ID zgłoszenia',
      category: 'Kategoria',
      opener: 'Otworzył',
      closedBy: 'Zamknął',
      totalMessages: 'Wiadomości',
      participants: 'Uczestnicy',
      attachmentsEmbeds: 'Załączniki / Osadzone',
      duration: 'Czas trwania'
    },
    participants: {
      title: 'Uczestnicy',
      users: 'Użytkownicy ({count})',
      bots: 'Boty ({count})',
      none: 'Brak',
      staff: 'STAFF'
    },
    viewers: {
      title: 'Kto mógł widzieć ten kanał',
      roles: 'Role ({count})',
      users: 'Użytkownicy ({count})',
      bots: 'Boty ({count})',
      none: 'Brak'
    },
    reply: {
      label: 'Odpowiedź → wiadomość {id}',
      hoverTitle: 'Kliknij, aby przejść do oryginalnej wiadomości',
      notFound: 'Nie znaleziono oryginalnej wiadomości'
    },
    reactions: {
      reactedBy: 'Zareagowali ({count})',
      overflow: '+{count} więcej',
      noUsers: 'Brak danych o reakcjach',
      noUsersTooltip: 'Brak informacji'
    },
    modal: {
      close: 'Zamknij',
      id: 'ID',
      joined: 'Dołączył',
      roles: 'Role',
      permissions: 'Uprawnienia',
      unknown: 'Nieznany',
      noRoles: 'Brak ról',
      noPermissions: 'Brak uprawnień',
      bot: 'BOT',
      staff: 'STAFF'
    },
    contextMenu: {
      viewProfile: 'Zobacz profil',
      copyUserId: 'Kopiuj ID użytkownika',
      copyUsername: 'Kopiuj nazwę użytkownika',
      message: 'Wiadomość',
      copyMessageId: 'Kopiuj ID wiadomości',
      copyMessageText: 'Kopiuj tekst wiadomości',
      copyMessageLink: 'Kopiuj link wiadomości'
    },
    toast: { copied: 'Skopiowano' },
    messages: { edited: '(edytowane)', systemMessage: '(wiadomość systemowa type={type})' },
    footer: 'Generated by discord-ticket-transcript v{version} · {time}'
  },
  duration: { days: 'd', hours: 'godz', minutes: 'min', seconds: 's' },
  permissions: {
    CreateInstantInvite: 'Twórz zaproszenia',
    KickMembers: 'Wyrzucaj użytkowników',
    BanMembers: 'Banuj użytkowników',
    Administrator: 'Administrator',
    ManageChannels: 'Zarządzaj kanałami',
    ManageGuild: 'Zarządzaj serwerem',
    AddReactions: 'Dodawaj reakcje',
    ViewAuditLog: 'Zobacz dziennik audytu',
    PrioritySpeaker: 'Mówca priorytetowy',
    Stream: 'Wideo',
    ViewChannel: 'Zobacz kanał',
    SendMessages: 'Wysyłaj wiadomości',
    SendTTSMessages: 'Wysyłaj wiadomości TTS',
    ManageMessages: 'Zarządzaj wiadomościami',
    EmbedLinks: 'Osadzaj linki',
    AttachFiles: 'Załączaj pliki',
    ReadMessageHistory: 'Czytaj historię wiadomości',
    MentionEveryone: 'Wspominaj @everyone, @here i wszystkie role',
    UseExternalEmojis: 'Używaj zewnętrznych emoji',
    ViewGuildInsights: 'Zobacz statystyki serwera',
    Connect: 'Połącz',
    Speak: 'Mów',
    MuteMembers: 'Wycisz użytkowników',
    DeafenMembers: 'Ogłusz użytkowników',
    MoveMembers: 'Przenoś użytkowników',
    UseVAD: 'Wykrywanie głosu',
    ChangeNickname: 'Zmień pseudonim',
    ManageNicknames: 'Zarządzaj pseudonimami',
    ManageRoles: 'Zarządzaj rolami',
    ManageWebhooks: 'Zarządzaj webhookami',
    ManageEmojisAndStickers: 'Zarządzaj emoji i naklejkami',
    ManageGuildExpressions: 'Zarządzaj ekspresjami',
    UseApplicationCommands: 'Używaj poleceń aplikacji',
    RequestToSpeak: 'Poproś o głos',
    ManageEvents: 'Zarządzaj wydarzeniami',
    ManageThreads: 'Zarządzaj wątkami',
    CreatePublicThreads: 'Twórz wątki publiczne',
    CreatePrivateThreads: 'Twórz wątki prywatne',
    UseExternalStickers: 'Używaj zewnętrznych naklejek',
    SendMessagesInThreads: 'Wysyłaj wiadomości w wątkach',
    UseEmbeddedActivities: 'Używaj aktywności',
    ModerateMembers: 'Czasowo wyciszaj',
    ViewCreatorMonetizationAnalytics: 'Zobacz analitykę monetyzacji',
    UseSoundboard: 'Używaj tablicy dźwięków',
    UseExternalSounds: 'Używaj zewnętrznych dźwięków',
    SendVoiceMessages: 'Wysyłaj wiadomości głosowe',
    SendPolls: 'Twórz ankiety',
    CreateEvents: 'Twórz wydarzenia',
    CreateGuildExpressions: 'Twórz ekspresje',
    UseExternalApps: 'Używaj zewnętrznych aplikacji'
  }
}
