import { Translations } from './types'

export const ptBR: Translations = {
  code: 'pt-BR',
  name: 'Português (Brasil)',
  ui: {
    header: {
      detailsToggle: '📊 Detalhes',
      themeToggle: '🌓 Tema',
      downloadJson: '📦 JSON',
      downloadText: '📄 TXT',
      languageLabel: 'Idioma'
    },
    summary: {
      ticketId: 'ID do ticket',
      category: 'Categoria',
      opener: 'Aberto por',
      closedBy: 'Fechado por',
      totalMessages: 'Mensagens',
      participants: 'Participantes',
      attachmentsEmbeds: 'Anexos / Embeds',
      duration: 'Duração'
    },
    participants: {
      title: 'Participantes',
      users: 'Usuários ({count})',
      bots: 'Bots ({count})',
      none: 'Nenhum',
      staff: 'STAFF'
    },
    viewers: {
      title: 'Quem podia ver este canal',
      roles: 'Cargos ({count})',
      users: 'Usuários ({count})',
      bots: 'Bots ({count})',
      none: 'Nenhum'
    },
    reply: {
      label: 'Resposta → mensagem {id}',
      hoverTitle: 'Clique para ir até a mensagem original',
      notFound: 'Mensagem original não encontrada'
    },
    reactions: {
      reactedBy: 'Reagiram ({count})',
      overflow: '+{count} mais',
      noUsers: 'Informações de reação não coletadas',
      noUsersTooltip: 'Sem informação de reação'
    },
    modal: {
      close: 'Fechar',
      id: 'ID',
      joined: 'Entrou em',
      roles: 'Cargos',
      permissions: 'Permissões',
      unknown: 'Desconhecido',
      noRoles: 'Sem cargos',
      noPermissions: 'Sem permissões',
      bot: 'BOT',
      staff: 'STAFF'
    },
    contextMenu: {
      viewProfile: 'Ver perfil',
      copyUserId: 'Copiar ID do usuário',
      copyUsername: 'Copiar nome de usuário',
      message: 'Mensagem',
      copyMessageId: 'Copiar ID da mensagem',
      copyMessageText: 'Copiar texto da mensagem',
      copyMessageLink: 'Copiar link da mensagem'
    },
    toast: { copied: 'Copiado' },
    messages: { edited: '(editado)', systemMessage: '(mensagem do sistema type={type})' },
    footer: 'Generated by discord-ticket-transcript v{version} · {time}'
  },
  duration: { days: 'd', hours: 'h', minutes: 'm', seconds: 's' },
  permissions: {
    CreateInstantInvite: 'Criar convite',
    KickMembers: 'Expulsar membros',
    BanMembers: 'Banir membros',
    Administrator: 'Administrador',
    ManageChannels: 'Gerenciar canais',
    ManageGuild: 'Gerenciar servidor',
    AddReactions: 'Adicionar reações',
    ViewAuditLog: 'Ver registro de auditoria',
    PrioritySpeaker: 'Orador prioritário',
    Stream: 'Vídeo',
    ViewChannel: 'Ver canal',
    SendMessages: 'Enviar mensagens',
    SendTTSMessages: 'Enviar mensagens de TTS',
    ManageMessages: 'Gerenciar mensagens',
    EmbedLinks: 'Incorporar links',
    AttachFiles: 'Anexar arquivos',
    ReadMessageHistory: 'Ler histórico de mensagens',
    MentionEveryone: 'Mencionar @everyone, @here e todos os cargos',
    UseExternalEmojis: 'Usar emojis externos',
    ViewGuildInsights: 'Ver insights do servidor',
    Connect: 'Conectar',
    Speak: 'Falar',
    MuteMembers: 'Silenciar membros',
    DeafenMembers: 'Ensurdecer membros',
    MoveMembers: 'Mover membros',
    UseVAD: 'Usar detecção de voz',
    ChangeNickname: 'Alterar apelido',
    ManageNicknames: 'Gerenciar apelidos',
    ManageRoles: 'Gerenciar cargos',
    ManageWebhooks: 'Gerenciar webhooks',
    ManageEmojisAndStickers: 'Gerenciar emojis e figurinhas',
    ManageGuildExpressions: 'Gerenciar expressões',
    UseApplicationCommands: 'Usar comandos de aplicativo',
    RequestToSpeak: 'Pedir para falar',
    ManageEvents: 'Gerenciar eventos',
    ManageThreads: 'Gerenciar tópicos',
    CreatePublicThreads: 'Criar tópicos públicos',
    CreatePrivateThreads: 'Criar tópicos privados',
    UseExternalStickers: 'Usar figurinhas externas',
    SendMessagesInThreads: 'Enviar mensagens em tópicos',
    UseEmbeddedActivities: 'Usar atividades',
    ModerateMembers: 'Colocar membros em tempo limite',
    ViewCreatorMonetizationAnalytics: 'Ver análises de monetização',
    UseSoundboard: 'Usar painel de sons',
    UseExternalSounds: 'Usar sons externos',
    SendVoiceMessages: 'Enviar mensagens de voz',
    SendPolls: 'Criar enquetes',
    CreateEvents: 'Criar eventos',
    CreateGuildExpressions: 'Criar expressões',
    UseExternalApps: 'Usar apps externos'
  }
}
