import { Translations } from './types'

export const ru: Translations = {
  code: 'ru',
  name: 'Русский',
  ui: {
    header: {
      detailsToggle: '📊 Подробности',
      themeToggle: '🌓 Тема',
      downloadJson: '📦 JSON',
      downloadText: '📄 TXT',
      languageLabel: 'Язык'
    },
    summary: {
      ticketId: 'ID тикета',
      category: 'Категория',
      opener: 'Открыл',
      closedBy: 'Закрыл',
      totalMessages: 'Сообщений',
      participants: 'Участники',
      attachmentsEmbeds: 'Вложения / Встраивания',
      duration: 'Длительность'
    },
    participants: {
      title: 'Участники',
      users: 'Пользователи ({count})',
      bots: 'Боты ({count})',
      none: 'Нет',
      staff: 'STAFF'
    },
    viewers: {
      title: 'Кто мог видеть этот канал',
      roles: 'Роли ({count})',
      users: 'Пользователи ({count})',
      bots: 'Боты ({count})',
      none: 'Нет'
    },
    reply: {
      label: 'Ответ → сообщение {id}',
      hoverTitle: 'Нажмите, чтобы перейти к оригиналу',
      notFound: 'Оригинальное сообщение не найдено'
    },
    reactions: {
      reactedBy: 'Реакции ({count})',
      overflow: 'и ещё {count}',
      noUsers: 'Не удалось получить информацию о реакциях',
      noUsersTooltip: 'Нет данных о реакциях'
    },
    modal: {
      close: 'Закрыть',
      id: 'ID',
      joined: 'Присоединился',
      roles: 'Роли',
      permissions: 'Права',
      unknown: 'Неизвестно',
      noRoles: 'Нет ролей',
      noPermissions: 'Нет прав',
      bot: 'BOT',
      staff: 'STAFF'
    },
    contextMenu: {
      viewProfile: 'Профиль',
      copyUserId: 'Копировать ID пользователя',
      copyUsername: 'Копировать имя пользователя',
      message: 'Сообщение',
      copyMessageId: 'Копировать ID сообщения',
      copyMessageText: 'Копировать текст сообщения',
      copyMessageLink: 'Копировать ссылку на сообщение'
    },
    toast: { copied: 'Скопировано' },
    messages: { edited: '(изменено)', systemMessage: '(системное сообщение type={type})' },
    footer: 'Generated by discord-ticket-transcript v{version} · {time}'
  },
  duration: { days: 'д', hours: 'ч', minutes: 'мин', seconds: 'с' },
  permissions: {
    CreateInstantInvite: 'Создавать приглашения',
    KickMembers: 'Выгонять участников',
    BanMembers: 'Банить участников',
    Administrator: 'Администратор',
    ManageChannels: 'Управлять каналами',
    ManageGuild: 'Управлять сервером',
    AddReactions: 'Добавлять реакции',
    ViewAuditLog: 'Просмотр журнала аудита',
    PrioritySpeaker: 'Приоритетный оратор',
    Stream: 'Видео',
    ViewChannel: 'Видеть канал',
    SendMessages: 'Отправлять сообщения',
    SendTTSMessages: 'Отправлять TTS-сообщения',
    ManageMessages: 'Управлять сообщениями',
    EmbedLinks: 'Встраивание ссылок',
    AttachFiles: 'Прикреплять файлы',
    ReadMessageHistory: 'Читать историю сообщений',
    MentionEveryone: 'Упоминать @everyone, @here и все роли',
    UseExternalEmojis: 'Использовать внешние эмодзи',
    ViewGuildInsights: 'Статистика сервера',
    Connect: 'Подключаться',
    Speak: 'Говорить',
    MuteMembers: 'Заглушать участников',
    DeafenMembers: 'Оглушать участников',
    MoveMembers: 'Перемещать участников',
    UseVAD: 'Определение голоса',
    ChangeNickname: 'Менять никнейм',
    ManageNicknames: 'Управлять никнеймами',
    ManageRoles: 'Управлять ролями',
    ManageWebhooks: 'Управлять вебхуками',
    ManageEmojisAndStickers: 'Управлять эмодзи и стикерами',
    ManageGuildExpressions: 'Управлять выражениями',
    UseApplicationCommands: 'Использовать команды приложений',
    RequestToSpeak: 'Запрос на выступление',
    ManageEvents: 'Управлять событиями',
    ManageThreads: 'Управлять ветками',
    CreatePublicThreads: 'Создавать публичные ветки',
    CreatePrivateThreads: 'Создавать приватные ветки',
    UseExternalStickers: 'Использовать внешние стикеры',
    SendMessagesInThreads: 'Писать в ветках',
    UseEmbeddedActivities: 'Использовать активности',
    ModerateMembers: 'Таймаут участников',
    ViewCreatorMonetizationAnalytics: 'Аналитика монетизации',
    UseSoundboard: 'Использовать звуковую панель',
    UseExternalSounds: 'Использовать внешние звуки',
    SendVoiceMessages: 'Отправлять голосовые сообщения',
    SendPolls: 'Создавать опросы',
    CreateEvents: 'Создавать события',
    CreateGuildExpressions: 'Создавать выражения',
    UseExternalApps: 'Использовать внешние приложения'
  }
}
