import { Translations } from './types'

export const sv: Translations = {
  code: 'sv',
  name: 'Svenska',
  ui: {
    header: {
      detailsToggle: '📊 Detaljer',
      themeToggle: '🌓 Tema',
      downloadJson: '📦 JSON',
      downloadText: '📄 TXT',
      languageLabel: 'Språk'
    },
    summary: {
      ticketId: 'Ticket-ID',
      category: 'Kategori',
      opener: 'Öppnad av',
      closedBy: 'Stängd av',
      totalMessages: 'Meddelanden',
      participants: 'Deltagare',
      attachmentsEmbeds: 'Bilagor / Inbäddade',
      duration: 'Varaktighet'
    },
    participants: {
      title: 'Deltagare',
      users: 'Användare ({count})',
      bots: 'Bottar ({count})',
      none: 'Inga',
      staff: 'STAFF'
    },
    viewers: {
      title: 'Vem kunde se den här kanalen',
      roles: 'Roller ({count})',
      users: 'Användare ({count})',
      bots: 'Bottar ({count})',
      none: 'Inga'
    },
    reply: {
      label: 'Svar → meddelande {id}',
      hoverTitle: 'Klicka för att gå till originalet',
      notFound: 'Originalmeddelandet hittades inte'
    },
    reactions: {
      reactedBy: 'Reaktioner ({count})',
      overflow: '+{count} till',
      noUsers: 'Reaktionsinformation saknas',
      noUsersTooltip: 'Ingen information'
    },
    modal: {
      close: 'Stäng',
      id: 'ID',
      joined: 'Gick med',
      roles: 'Roller',
      permissions: 'Behörigheter',
      unknown: 'Okänd',
      noRoles: 'Inga roller',
      noPermissions: 'Inga behörigheter',
      bot: 'BOT',
      staff: 'STAFF'
    },
    contextMenu: {
      viewProfile: 'Visa profil',
      copyUserId: 'Kopiera användar-ID',
      copyUsername: 'Kopiera användarnamn',
      message: 'Meddelande',
      copyMessageId: 'Kopiera meddelande-ID',
      copyMessageText: 'Kopiera meddelandetext',
      copyMessageLink: 'Kopiera meddelandelänk'
    },
    toast: { copied: 'Kopierat' },
    messages: { edited: '(redigerat)', systemMessage: '(systemmeddelande type={type})' },
    footer: 'Generated by discord-ticket-transcript v{version} · {time}'
  },
  duration: { days: 'd', hours: 'tim', minutes: 'min', seconds: 's' },
  permissions: {
    CreateInstantInvite: 'Skapa inbjudan',
    KickMembers: 'Sparka medlemmar',
    BanMembers: 'Banna medlemmar',
    Administrator: 'Administratör',
    ManageChannels: 'Hantera kanaler',
    ManageGuild: 'Hantera server',
    AddReactions: 'Lägg till reaktioner',
    ViewAuditLog: 'Visa granskningslogg',
    PrioritySpeaker: 'Prioritetstalare',
    Stream: 'Video',
    ViewChannel: 'Visa kanal',
    SendMessages: 'Skicka meddelanden',
    SendTTSMessages: 'Skicka TTS-meddelanden',
    ManageMessages: 'Hantera meddelanden',
    EmbedLinks: 'Bädda in länkar',
    AttachFiles: 'Bifoga filer',
    ReadMessageHistory: 'Läs meddelandehistorik',
    MentionEveryone: 'Nämn @everyone, @here och alla roller',
    UseExternalEmojis: 'Använd externa emojis',
    ViewGuildInsights: 'Visa serverstatistik',
    Connect: 'Anslut',
    Speak: 'Tala',
    MuteMembers: 'Tysta medlemmar',
    DeafenMembers: 'Dövsätt medlemmar',
    MoveMembers: 'Flytta medlemmar',
    UseVAD: 'Röstaktivitetsdetektering',
    ChangeNickname: 'Ändra smeknamn',
    ManageNicknames: 'Hantera smeknamn',
    ManageRoles: 'Hantera roller',
    ManageWebhooks: 'Hantera webhooks',
    ManageEmojisAndStickers: 'Hantera emojis och dekaler',
    ManageGuildExpressions: 'Hantera uttryck',
    UseApplicationCommands: 'Använd appkommandon',
    RequestToSpeak: 'Begär att tala',
    ManageEvents: 'Hantera evenemang',
    ManageThreads: 'Hantera trådar',
    CreatePublicThreads: 'Skapa offentliga trådar',
    CreatePrivateThreads: 'Skapa privata trådar',
    UseExternalStickers: 'Använd externa dekaler',
    SendMessagesInThreads: 'Skicka meddelanden i trådar',
    UseEmbeddedActivities: 'Använd aktiviteter',
    ModerateMembers: 'Timeout av medlemmar',
    ViewCreatorMonetizationAnalytics: 'Visa skaparanalys',
    UseSoundboard: 'Använd ljudtavla',
    UseExternalSounds: 'Använd externa ljud',
    SendVoiceMessages: 'Skicka röstmeddelanden',
    SendPolls: 'Skapa omröstningar',
    CreateEvents: 'Skapa evenemang',
    CreateGuildExpressions: 'Skapa uttryck',
    UseExternalApps: 'Använd externa appar'
  }
}
