import { Translations } from './types'

export const th: Translations = {
  code: 'th',
  name: 'ไทย',
  ui: {
    header: {
      detailsToggle: '📊 รายละเอียด',
      themeToggle: '🌓 ธีม',
      downloadJson: '📦 JSON',
      downloadText: '📄 TXT',
      languageLabel: 'ภาษา'
    },
    summary: {
      ticketId: 'รหัสตั๋ว',
      category: 'หมวดหมู่',
      opener: 'เปิดโดย',
      closedBy: 'ปิดโดย',
      totalMessages: 'ข้อความ',
      participants: 'ผู้เข้าร่วม',
      attachmentsEmbeds: 'ไฟล์แนบ / ฝังตัว',
      duration: 'ระยะเวลา'
    },
    participants: {
      title: 'ผู้เข้าร่วม',
      users: 'ผู้ใช้ ({count})',
      bots: 'บอท ({count})',
      none: 'ไม่มี',
      staff: 'STAFF'
    },
    viewers: {
      title: 'ผู้ที่สามารถดูช่องนี้ได้',
      roles: 'บทบาท ({count})',
      users: 'ผู้ใช้ ({count})',
      bots: 'บอท ({count})',
      none: 'ไม่มี'
    },
    reply: {
      label: 'ตอบกลับ → ข้อความ {id}',
      hoverTitle: 'คลิกเพื่อไปยังข้อความต้นฉบับ',
      notFound: 'ไม่พบข้อความต้นฉบับ'
    },
    reactions: {
      reactedBy: 'รีแอค ({count})',
      overflow: '+{count} อื่นๆ',
      noUsers: 'ไม่มีข้อมูลรีแอค',
      noUsersTooltip: 'ไม่มีข้อมูล'
    },
    modal: {
      close: 'ปิด',
      id: 'ID',
      joined: 'เข้าร่วม',
      roles: 'บทบาท',
      permissions: 'สิทธิ์',
      unknown: 'ไม่ทราบ',
      noRoles: 'ไม่มีบทบาท',
      noPermissions: 'ไม่มีสิทธิ์',
      bot: 'BOT',
      staff: 'STAFF'
    },
    contextMenu: {
      viewProfile: 'ดูโปรไฟล์',
      copyUserId: 'คัดลอก ID ผู้ใช้',
      copyUsername: 'คัดลอกชื่อผู้ใช้',
      message: 'ข้อความ',
      copyMessageId: 'คัดลอก ID ข้อความ',
      copyMessageText: 'คัดลอกข้อความ',
      copyMessageLink: 'คัดลอกลิงก์ข้อความ'
    },
    toast: { copied: 'คัดลอกแล้ว' },
    messages: { edited: '(แก้ไขแล้ว)', systemMessage: '(ข้อความระบบ type={type})' },
    footer: 'Generated by discord-ticket-transcript v{version} · {time}'
  },
  duration: { days: 'วัน', hours: 'ชม.', minutes: 'น.', seconds: 'วิ' },
  permissions: {
    CreateInstantInvite: 'สร้างคำเชิญ',
    KickMembers: 'ไล่สมาชิก',
    BanMembers: 'แบนสมาชิก',
    Administrator: 'ผู้ดูแลระบบ',
    ManageChannels: 'จัดการช่อง',
    ManageGuild: 'จัดการเซิร์ฟเวอร์',
    AddReactions: 'เพิ่มรีแอค',
    ViewAuditLog: 'ดูบันทึกตรวจสอบ',
    PrioritySpeaker: 'ผู้พูดลำดับสูง',
    Stream: 'วิดีโอ',
    ViewChannel: 'ดูช่อง',
    SendMessages: 'ส่งข้อความ',
    SendTTSMessages: 'ส่งข้อความ TTS',
    ManageMessages: 'จัดการข้อความ',
    EmbedLinks: 'ฝังลิงก์',
    AttachFiles: 'แนบไฟล์',
    ReadMessageHistory: 'อ่านประวัติข้อความ',
    MentionEveryone: 'พูดถึง @everyone, @here และทุกบทบาท',
    UseExternalEmojis: 'ใช้อีโมจิภายนอก',
    ViewGuildInsights: 'ดูสถิติเซิร์ฟเวอร์',
    Connect: 'เชื่อมต่อ',
    Speak: 'พูด',
    MuteMembers: 'ปิดเสียงสมาชิก',
    DeafenMembers: 'ปิดการได้ยินสมาชิก',
    MoveMembers: 'ย้ายสมาชิก',
    UseVAD: 'ใช้การตรวจเสียง',
    ChangeNickname: 'เปลี่ยนชื่อเล่น',
    ManageNicknames: 'จัดการชื่อเล่น',
    ManageRoles: 'จัดการบทบาท',
    ManageWebhooks: 'จัดการ Webhook',
    ManageEmojisAndStickers: 'จัดการอีโมจิและสติ๊กเกอร์',
    ManageGuildExpressions: 'จัดการการแสดงออก',
    UseApplicationCommands: 'ใช้คำสั่งแอป',
    RequestToSpeak: 'ขอพูด',
    ManageEvents: 'จัดการกิจกรรม',
    ManageThreads: 'จัดการเธรด',
    CreatePublicThreads: 'สร้างเธรดสาธารณะ',
    CreatePrivateThreads: 'สร้างเธรดส่วนตัว',
    UseExternalStickers: 'ใช้สติ๊กเกอร์ภายนอก',
    SendMessagesInThreads: 'ส่งข้อความในเธรด',
    UseEmbeddedActivities: 'ใช้กิจกรรม',
    ModerateMembers: 'ไทม์เอาต์สมาชิก',
    ViewCreatorMonetizationAnalytics: 'ดูการวิเคราะห์การสร้างรายได้',
    UseSoundboard: 'ใช้ Soundboard',
    UseExternalSounds: 'ใช้เสียงภายนอก',
    SendVoiceMessages: 'ส่งข้อความเสียง',
    SendPolls: 'สร้างโพล',
    CreateEvents: 'สร้างกิจกรรม',
    CreateGuildExpressions: 'สร้างการแสดงออก',
    UseExternalApps: 'ใช้แอปภายนอก'
  }
}
