import { Translations } from './types'

export const tr: Translations = {
  code: 'tr',
  name: 'Türkçe',
  ui: {
    header: {
      detailsToggle: '📊 Ayrıntılar',
      themeToggle: '🌓 Tema',
      downloadJson: '📦 JSON',
      downloadText: '📄 TXT',
      languageLabel: 'Dil'
    },
    summary: {
      ticketId: 'Ticket ID',
      category: 'Kategori',
      opener: 'Açan',
      closedBy: 'Kapatan',
      totalMessages: 'Mesaj',
      participants: 'Katılımcılar',
      attachmentsEmbeds: 'Ekler / Gömülüler',
      duration: 'Süre'
    },
    participants: {
      title: 'Katılımcılar',
      users: 'Kullanıcı ({count})',
      bots: 'Bot ({count})',
      none: 'Yok',
      staff: 'STAFF'
    },
    viewers: {
      title: 'Bu kanalı görebilenler',
      roles: 'Rol ({count})',
      users: 'Kullanıcı ({count})',
      bots: 'Bot ({count})',
      none: 'Yok'
    },
    reply: {
      label: 'Yanıt → mesaj {id}',
      hoverTitle: 'Orijinal mesaja gitmek için tıklayın',
      notFound: 'Orijinal mesaj bulunamadı'
    },
    reactions: {
      reactedBy: 'Tepki verenler ({count})',
      overflow: '+{count} daha',
      noUsers: 'Tepki bilgileri toplanmadı',
      noUsersTooltip: 'Tepki bilgisi yok'
    },
    modal: {
      close: 'Kapat',
      id: 'ID',
      joined: 'Katılma',
      roles: 'Roller',
      permissions: 'İzinler',
      unknown: 'Bilinmiyor',
      noRoles: 'Rol yok',
      noPermissions: 'İzin yok',
      bot: 'BOT',
      staff: 'STAFF'
    },
    contextMenu: {
      viewProfile: 'Profili gör',
      copyUserId: 'Kullanıcı ID kopyala',
      copyUsername: 'Kullanıcı adı kopyala',
      message: 'Mesaj',
      copyMessageId: 'Mesaj ID kopyala',
      copyMessageText: 'Mesaj metnini kopyala',
      copyMessageLink: 'Mesaj linkini kopyala'
    },
    toast: { copied: 'Kopyalandı' },
    messages: { edited: '(düzenlendi)', systemMessage: '(sistem mesajı type={type})' },
    footer: 'Generated by discord-ticket-transcript v{version} · {time}'
  },
  duration: { days: 'g', hours: 's', minutes: 'dk', seconds: 'sn' },
  permissions: {
    CreateInstantInvite: 'Davet oluştur',
    KickMembers: 'Üyeleri at',
    BanMembers: 'Üyeleri yasakla',
    Administrator: 'Yönetici',
    ManageChannels: 'Kanalları yönet',
    ManageGuild: 'Sunucuyu yönet',
    AddReactions: 'Tepki ekle',
    ViewAuditLog: 'Denetim kaydını gör',
    PrioritySpeaker: 'Öncelikli konuşmacı',
    Stream: 'Video',
    ViewChannel: 'Kanalı gör',
    SendMessages: 'Mesaj gönder',
    SendTTSMessages: 'TTS mesaj gönder',
    ManageMessages: 'Mesajları yönet',
    EmbedLinks: 'Bağlantı göm',
    AttachFiles: 'Dosya ekle',
    ReadMessageHistory: 'Mesaj geçmişini oku',
    MentionEveryone: '@everyone, @here ve tüm rolleri bahset',
    UseExternalEmojis: 'Harici emoji kullan',
    ViewGuildInsights: 'Sunucu istatistiklerini gör',
    Connect: 'Bağlan',
    Speak: 'Konuş',
    MuteMembers: 'Üyeleri sustur',
    DeafenMembers: 'Üyeleri sağırlaştır',
    MoveMembers: 'Üyeleri taşı',
    UseVAD: 'Ses algılama kullan',
    ChangeNickname: 'Takma ad değiştir',
    ManageNicknames: 'Takma adları yönet',
    ManageRoles: 'Rolleri yönet',
    ManageWebhooks: 'Webhookları yönet',
    ManageEmojisAndStickers: 'Emoji ve çıkartmaları yönet',
    ManageGuildExpressions: 'İfadeleri yönet',
    UseApplicationCommands: 'Uygulama komutlarını kullan',
    RequestToSpeak: 'Konuşma isteği',
    ManageEvents: 'Etkinlikleri yönet',
    ManageThreads: 'Başlıkları yönet',
    CreatePublicThreads: 'Herkese açık başlık oluştur',
    CreatePrivateThreads: 'Özel başlık oluştur',
    UseExternalStickers: 'Harici çıkartma kullan',
    SendMessagesInThreads: 'Başlıklarda mesaj gönder',
    UseEmbeddedActivities: 'Etkinlikleri kullan',
    ModerateMembers: 'Üyeleri zaman aşımına al',
    ViewCreatorMonetizationAnalytics: 'Yaratıcı analiz',
    UseSoundboard: 'Ses tahtası kullan',
    UseExternalSounds: 'Harici ses kullan',
    SendVoiceMessages: 'Sesli mesaj gönder',
    SendPolls: 'Anket oluştur',
    CreateEvents: 'Etkinlik oluştur',
    CreateGuildExpressions: 'İfade oluştur',
    UseExternalApps: 'Harici uygulama kullan'
  }
}
