/**
 * 번역 사전 구조. 메시지 본문과 사용자 정보는 i18n 대상 아님.
 * 모든 UI chrome(헤더/카드/모달/메뉴/토스트 등)과 권한 라벨만 번역.
 */
export interface Translations {
  /** BCP-47 코드 (ko, en, ja, zh-CN …) */
  code: string
  /** 언어 선택 메뉴에 표시될 원어 이름 (한국어, English, 日本語, 中文 …) */
  name: string
  ui: {
    header: {
      detailsToggle: string
      themeToggle: string
      downloadJson: string
      downloadText: string
      languageLabel: string
    }
    summary: {
      ticketId: string
      category: string
      opener: string
      closedBy: string
      totalMessages: string
      participants: string
      attachmentsEmbeds: string
      duration: string
    }
    participants: {
      title: string
      users: string
      bots: string
      none: string
      staff: string
    }
    viewers: {
      title: string
      roles: string
      users: string
      bots: string
      none: string
    }
    reply: {
      label: string // "Reply → message {id}"
      hoverTitle: string
      notFound: string
    }
    reactions: {
      reactedBy: string // "Reacted ({count})"
      overflow: string // "+{count} more"
      noUsers: string
      noUsersTooltip: string
    }
    modal: {
      close: string
      id: string
      joined: string
      roles: string
      permissions: string
      unknown: string
      noRoles: string
      noPermissions: string
      bot: string
      staff: string
    }
    contextMenu: {
      viewProfile: string
      copyUserId: string
      copyUsername: string
      message: string
      copyMessageId: string
      copyMessageText: string
      copyMessageLink: string
    }
    toast: {
      copied: string
    }
    messages: {
      edited: string
      systemMessage: string // "(system message type={type})"
    }
    footer: string // "Generated by … v{version} · {time}"
  }
  /** Discord 권한 API 이름 → 현지화 이름 */
  permissions: Record<string, string>
  /** "n시간 m분" 형태의 지속 시간 단위 */
  duration: {
    days: string
    hours: string
    minutes: string
    seconds: string
  }
}
