import { Translations } from './types'

export const uk: Translations = {
  code: 'uk',
  name: 'Українська',
  ui: {
    header: {
      detailsToggle: '📊 Деталі',
      themeToggle: '🌓 Тема',
      downloadJson: '📦 JSON',
      downloadText: '📄 TXT',
      languageLabel: 'Мова'
    },
    summary: {
      ticketId: 'ID тікета',
      category: 'Категорія',
      opener: 'Відкрив',
      closedBy: 'Закрив',
      totalMessages: 'Повідомлень',
      participants: 'Учасники',
      attachmentsEmbeds: 'Вкладення / Вбудовування',
      duration: 'Тривалість'
    },
    participants: {
      title: 'Учасники',
      users: 'Користувачі ({count})',
      bots: 'Боти ({count})',
      none: 'Немає',
      staff: 'STAFF'
    },
    viewers: {
      title: 'Хто міг бачити цей канал',
      roles: 'Ролі ({count})',
      users: 'Користувачі ({count})',
      bots: 'Боти ({count})',
      none: 'Немає'
    },
    reply: {
      label: 'Відповідь → повідомлення {id}',
      hoverTitle: 'Клацніть, щоб перейти до оригіналу',
      notFound: 'Оригінальне повідомлення не знайдено'
    },
    reactions: {
      reactedBy: 'Реакції ({count})',
      overflow: 'ще {count}',
      noUsers: 'Немає даних про реакції',
      noUsersTooltip: 'Немає даних'
    },
    modal: {
      close: 'Закрити',
      id: 'ID',
      joined: 'Приєднався',
      roles: 'Ролі',
      permissions: 'Права',
      unknown: 'Невідомо',
      noRoles: 'Немає ролей',
      noPermissions: 'Немає прав',
      bot: 'BOT',
      staff: 'STAFF'
    },
    contextMenu: {
      viewProfile: 'Переглянути профіль',
      copyUserId: 'Копіювати ID користувача',
      copyUsername: "Копіювати ім'я",
      message: 'Повідомлення',
      copyMessageId: 'Копіювати ID',
      copyMessageText: 'Копіювати текст',
      copyMessageLink: 'Копіювати посилання'
    },
    toast: { copied: 'Скопійовано' },
    messages: { edited: '(редаговано)', systemMessage: '(системне повідомлення type={type})' },
    footer: 'Generated by discord-ticket-transcript v{version} · {time}'
  },
  duration: { days: 'д', hours: 'год', minutes: 'хв', seconds: 'с' },
  permissions: {
    CreateInstantInvite: 'Створювати запрошення',
    KickMembers: 'Виганяти учасників',
    BanMembers: 'Банити учасників',
    Administrator: 'Адміністратор',
    ManageChannels: 'Керувати каналами',
    ManageGuild: 'Керувати сервером',
    AddReactions: 'Додавати реакції',
    ViewAuditLog: 'Переглядати журнал',
    PrioritySpeaker: 'Пріоритетний мовець',
    Stream: 'Відео',
    ViewChannel: 'Бачити канал',
    SendMessages: 'Надсилати повідомлення',
    SendTTSMessages: 'Надсилати TTS',
    ManageMessages: 'Керувати повідомленнями',
    EmbedLinks: 'Вбудовувати посилання',
    AttachFiles: 'Приєднувати файли',
    ReadMessageHistory: 'Читати історію',
    MentionEveryone: 'Згадувати @everyone, @here і всі ролі',
    UseExternalEmojis: 'Зовнішні емодзі',
    ViewGuildInsights: 'Статистика сервера',
    Connect: "Під'єднуватися",
    Speak: 'Говорити',
    MuteMembers: 'Заглушувати',
    DeafenMembers: 'Оглушувати',
    MoveMembers: 'Переміщати',
    UseVAD: 'Визначення голосу',
    ChangeNickname: 'Змінити нікнейм',
    ManageNicknames: 'Керувати нікнеймами',
    ManageRoles: 'Керувати ролями',
    ManageWebhooks: 'Керувати вебхуками',
    ManageEmojisAndStickers: 'Керувати емодзі та стікерами',
    ManageGuildExpressions: 'Керувати виразами',
    UseApplicationCommands: 'Використовувати команди',
    RequestToSpeak: 'Просити виступити',
    ManageEvents: 'Керувати подіями',
    ManageThreads: 'Керувати гілками',
    CreatePublicThreads: 'Створювати публічні гілки',
    CreatePrivateThreads: 'Створювати приватні гілки',
    UseExternalStickers: 'Зовнішні стікери',
    SendMessagesInThreads: 'Повідомлення в гілках',
    UseEmbeddedActivities: 'Активності',
    ModerateMembers: 'Таймаут учасників',
    ViewCreatorMonetizationAnalytics: 'Аналітика монетизації',
    UseSoundboard: 'Звукова панель',
    UseExternalSounds: 'Зовнішні звуки',
    SendVoiceMessages: 'Голосові повідомлення',
    SendPolls: 'Опитування',
    CreateEvents: 'Створювати події',
    CreateGuildExpressions: 'Створювати вирази',
    UseExternalApps: 'Зовнішні додатки'
  }
}
