import { Translations } from './types'

export const vi: Translations = {
  code: 'vi',
  name: 'Tiếng Việt',
  ui: {
    header: {
      detailsToggle: '📊 Chi tiết',
      themeToggle: '🌓 Giao diện',
      downloadJson: '📦 JSON',
      downloadText: '📄 TXT',
      languageLabel: 'Ngôn ngữ'
    },
    summary: {
      ticketId: 'ID ticket',
      category: 'Danh mục',
      opener: 'Mở bởi',
      closedBy: 'Đóng bởi',
      totalMessages: 'Tin nhắn',
      participants: 'Người tham gia',
      attachmentsEmbeds: 'Tệp đính kèm / Nhúng',
      duration: 'Thời lượng'
    },
    participants: {
      title: 'Người tham gia',
      users: 'Người dùng ({count})',
      bots: 'Bot ({count})',
      none: 'Không có',
      staff: 'STAFF'
    },
    viewers: {
      title: 'Ai có thể thấy kênh này',
      roles: 'Vai trò ({count})',
      users: 'Người dùng ({count})',
      bots: 'Bot ({count})',
      none: 'Không có'
    },
    reply: {
      label: 'Trả lời → tin nhắn {id}',
      hoverTitle: 'Nhấp để đến tin nhắn gốc',
      notFound: 'Không tìm thấy tin nhắn gốc'
    },
    reactions: {
      reactedBy: 'Đã phản ứng ({count})',
      overflow: '+{count} nữa',
      noUsers: 'Không thu thập được thông tin phản ứng',
      noUsersTooltip: 'Không có thông tin'
    },
    modal: {
      close: 'Đóng',
      id: 'ID',
      joined: 'Tham gia',
      roles: 'Vai trò',
      permissions: 'Quyền',
      unknown: 'Không xác định',
      noRoles: 'Không có vai trò',
      noPermissions: 'Không có quyền',
      bot: 'BOT',
      staff: 'STAFF'
    },
    contextMenu: {
      viewProfile: 'Xem hồ sơ',
      copyUserId: 'Sao chép ID người dùng',
      copyUsername: 'Sao chép tên người dùng',
      message: 'Tin nhắn',
      copyMessageId: 'Sao chép ID tin nhắn',
      copyMessageText: 'Sao chép nội dung',
      copyMessageLink: 'Sao chép liên kết'
    },
    toast: { copied: 'Đã sao chép' },
    messages: { edited: '(đã chỉnh sửa)', systemMessage: '(tin nhắn hệ thống type={type})' },
    footer: 'Generated by discord-ticket-transcript v{version} · {time}'
  },
  duration: { days: 'n', hours: 'g', minutes: 'p', seconds: 'gi' },
  permissions: {
    CreateInstantInvite: 'Tạo lời mời',
    KickMembers: 'Đá thành viên',
    BanMembers: 'Cấm thành viên',
    Administrator: 'Quản trị viên',
    ManageChannels: 'Quản lý kênh',
    ManageGuild: 'Quản lý máy chủ',
    AddReactions: 'Thêm phản ứng',
    ViewAuditLog: 'Xem nhật ký',
    PrioritySpeaker: 'Người nói ưu tiên',
    Stream: 'Video',
    ViewChannel: 'Xem kênh',
    SendMessages: 'Gửi tin nhắn',
    SendTTSMessages: 'Gửi tin nhắn TTS',
    ManageMessages: 'Quản lý tin nhắn',
    EmbedLinks: 'Nhúng liên kết',
    AttachFiles: 'Đính kèm tệp',
    ReadMessageHistory: 'Đọc lịch sử tin nhắn',
    MentionEveryone: 'Nhắc @everyone, @here và tất cả vai trò',
    UseExternalEmojis: 'Dùng emoji ngoài',
    ViewGuildInsights: 'Xem thống kê máy chủ',
    Connect: 'Kết nối',
    Speak: 'Nói',
    MuteMembers: 'Tắt tiếng thành viên',
    DeafenMembers: 'Tắt nghe thành viên',
    MoveMembers: 'Di chuyển thành viên',
    UseVAD: 'Dùng phát hiện giọng nói',
    ChangeNickname: 'Đổi biệt danh',
    ManageNicknames: 'Quản lý biệt danh',
    ManageRoles: 'Quản lý vai trò',
    ManageWebhooks: 'Quản lý webhook',
    ManageEmojisAndStickers: 'Quản lý emoji và nhãn dán',
    ManageGuildExpressions: 'Quản lý biểu cảm',
    UseApplicationCommands: 'Dùng lệnh ứng dụng',
    RequestToSpeak: 'Yêu cầu phát biểu',
    ManageEvents: 'Quản lý sự kiện',
    ManageThreads: 'Quản lý chủ đề',
    CreatePublicThreads: 'Tạo chủ đề công khai',
    CreatePrivateThreads: 'Tạo chủ đề riêng',
    UseExternalStickers: 'Dùng nhãn dán ngoài',
    SendMessagesInThreads: 'Gửi tin trong chủ đề',
    UseEmbeddedActivities: 'Dùng hoạt động',
    ModerateMembers: 'Tạm ngừng thành viên',
    ViewCreatorMonetizationAnalytics: 'Xem phân tích kiếm tiền',
    UseSoundboard: 'Dùng bảng âm thanh',
    UseExternalSounds: 'Dùng âm thanh ngoài',
    SendVoiceMessages: 'Gửi tin nhắn thoại',
    SendPolls: 'Tạo khảo sát',
    CreateEvents: 'Tạo sự kiện',
    CreateGuildExpressions: 'Tạo biểu cảm',
    UseExternalApps: 'Dùng ứng dụng ngoài'
  }
}
