import { Translations } from './types'

export const zhCN: Translations = {
  code: 'zh-CN',
  name: '简体中文',
  ui: {
    header: {
      detailsToggle: '📊 详情',
      themeToggle: '🌓 主题',
      downloadJson: '📦 JSON',
      downloadText: '📄 TXT',
      languageLabel: '语言'
    },
    summary: {
      ticketId: '工单ID',
      category: '分类',
      opener: '开单人',
      closedBy: '关单人',
      totalMessages: '消息数',
      participants: '参与者',
      attachmentsEmbeds: '附件 / 嵌入',
      duration: '持续时间'
    },
    participants: {
      title: '参与者',
      users: '用户 ({count})',
      bots: '机器人 ({count})',
      none: '无',
      staff: 'STAFF'
    },
    viewers: {
      title: '可查看此频道的对象',
      roles: '身份组 ({count})',
      users: '用户 ({count})',
      bots: '机器人 ({count})',
      none: '无'
    },
    reply: {
      label: '回复 → 消息 {id}',
      hoverTitle: '点击跳转到原消息',
      notFound: '未找到原消息'
    },
    reactions: {
      reactedBy: '反应 ({count})',
      overflow: '等 {count} 人',
      noUsers: '未能获取反应者信息',
      noUsersTooltip: '无反应者信息'
    },
    modal: {
      close: '关闭',
      id: 'ID',
      joined: '加入时间',
      roles: '身份组',
      permissions: '权限',
      unknown: '未知',
      noRoles: '无身份组信息',
      noPermissions: '无权限信息',
      bot: 'BOT',
      staff: 'STAFF'
    },
    contextMenu: {
      viewProfile: '查看资料',
      copyUserId: '复制用户ID',
      copyUsername: '复制用户名',
      message: '消息',
      copyMessageId: '复制消息ID',
      copyMessageText: '复制消息文本',
      copyMessageLink: '复制消息链接'
    },
    toast: { copied: '已复制' },
    messages: { edited: '(已编辑)', systemMessage: '(系统消息 type={type})' },
    footer: 'Generated by discord-ticket-transcript v{version} · {time}'
  },
  duration: { days: '天', hours: '小时', minutes: '分', seconds: '秒' },
  permissions: {
    CreateInstantInvite: '创建邀请',
    KickMembers: '踢出成员',
    BanMembers: '封禁成员',
    Administrator: '管理员',
    ManageChannels: '管理频道',
    ManageGuild: '管理服务器',
    AddReactions: '添加反应',
    ViewAuditLog: '查看审核日志',
    PrioritySpeaker: '优先发言',
    Stream: '视频',
    ViewChannel: '查看频道',
    SendMessages: '发送消息',
    SendTTSMessages: '发送TTS消息',
    ManageMessages: '管理消息',
    EmbedLinks: '嵌入链接',
    AttachFiles: '附加文件',
    ReadMessageHistory: '读取消息历史',
    MentionEveryone: '提及 @everyone、@here 与所有身份组',
    UseExternalEmojis: '使用外部表情',
    ViewGuildInsights: '查看服务器洞察',
    Connect: '连接',
    Speak: '发言',
    MuteMembers: '禁言成员',
    DeafenMembers: '拒听成员',
    MoveMembers: '移动成员',
    UseVAD: '使用语音活动检测',
    ChangeNickname: '更改昵称',
    ManageNicknames: '管理昵称',
    ManageRoles: '管理身份组',
    ManageWebhooks: '管理Webhook',
    ManageEmojisAndStickers: '管理表情和贴纸',
    ManageGuildExpressions: '管理表达',
    UseApplicationCommands: '使用应用命令',
    RequestToSpeak: '申请发言',
    ManageEvents: '管理活动',
    ManageThreads: '管理话题',
    CreatePublicThreads: '创建公开话题',
    CreatePrivateThreads: '创建私密话题',
    UseExternalStickers: '使用外部贴纸',
    SendMessagesInThreads: '在话题中发送消息',
    UseEmbeddedActivities: '使用活动',
    ModerateMembers: '超时成员',
    ViewCreatorMonetizationAnalytics: '查看创作者收益分析',
    UseSoundboard: '使用音板',
    UseExternalSounds: '使用外部声音',
    SendVoiceMessages: '发送语音消息',
    SendPolls: '创建投票',
    CreateEvents: '创建活动',
    CreateGuildExpressions: '创建表达',
    UseExternalApps: '使用外部应用'
  }
}
