import { Translations } from './types'

export const zhTW: Translations = {
  code: 'zh-TW',
  name: '繁體中文',
  ui: {
    header: {
      detailsToggle: '📊 詳情',
      themeToggle: '🌓 主題',
      downloadJson: '📦 JSON',
      downloadText: '📄 TXT',
      languageLabel: '語言'
    },
    summary: {
      ticketId: '工單ID',
      category: '分類',
      opener: '開單者',
      closedBy: '關單者',
      totalMessages: '訊息數',
      participants: '參與者',
      attachmentsEmbeds: '附件 / 嵌入',
      duration: '持續時間'
    },
    participants: {
      title: '參與者',
      users: '使用者 ({count})',
      bots: '機器人 ({count})',
      none: '無',
      staff: 'STAFF'
    },
    viewers: {
      title: '可查看此頻道的對象',
      roles: '身分組 ({count})',
      users: '使用者 ({count})',
      bots: '機器人 ({count})',
      none: '無'
    },
    reply: {
      label: '回覆 → 訊息 {id}',
      hoverTitle: '點擊跳至原訊息',
      notFound: '找不到原訊息'
    },
    reactions: {
      reactedBy: '反應 ({count})',
      overflow: '等 {count} 人',
      noUsers: '未取得反應資訊',
      noUsersTooltip: '無反應資訊'
    },
    modal: {
      close: '關閉',
      id: 'ID',
      joined: '加入時間',
      roles: '身分組',
      permissions: '權限',
      unknown: '未知',
      noRoles: '無身分組資訊',
      noPermissions: '無權限資訊',
      bot: 'BOT',
      staff: 'STAFF'
    },
    contextMenu: {
      viewProfile: '查看資料',
      copyUserId: '複製使用者ID',
      copyUsername: '複製使用者名稱',
      message: '訊息',
      copyMessageId: '複製訊息ID',
      copyMessageText: '複製訊息內容',
      copyMessageLink: '複製訊息連結'
    },
    toast: { copied: '已複製' },
    messages: { edited: '(已編輯)', systemMessage: '(系統訊息 type={type})' },
    footer: 'Generated by discord-ticket-transcript v{version} · {time}'
  },
  duration: { days: '天', hours: '小時', minutes: '分', seconds: '秒' },
  permissions: {
    CreateInstantInvite: '建立邀請',
    KickMembers: '踢出成員',
    BanMembers: '封鎖成員',
    Administrator: '管理員',
    ManageChannels: '管理頻道',
    ManageGuild: '管理伺服器',
    AddReactions: '新增反應',
    ViewAuditLog: '查看審核日誌',
    PrioritySpeaker: '優先發言',
    Stream: '視訊',
    ViewChannel: '查看頻道',
    SendMessages: '傳送訊息',
    SendTTSMessages: '傳送TTS訊息',
    ManageMessages: '管理訊息',
    EmbedLinks: '嵌入連結',
    AttachFiles: '附加檔案',
    ReadMessageHistory: '讀取訊息歷史',
    MentionEveryone: '提及 @everyone、@here 與所有身分組',
    UseExternalEmojis: '使用外部表情',
    ViewGuildInsights: '查看伺服器洞察',
    Connect: '連線',
    Speak: '發言',
    MuteMembers: '禁言成員',
    DeafenMembers: '拒聽成員',
    MoveMembers: '移動成員',
    UseVAD: '語音活動檢測',
    ChangeNickname: '變更暱稱',
    ManageNicknames: '管理暱稱',
    ManageRoles: '管理身分組',
    ManageWebhooks: '管理Webhook',
    ManageEmojisAndStickers: '管理表情與貼圖',
    ManageGuildExpressions: '管理表達',
    UseApplicationCommands: '使用應用程式指令',
    RequestToSpeak: '請求發言',
    ManageEvents: '管理活動',
    ManageThreads: '管理話題',
    CreatePublicThreads: '建立公開話題',
    CreatePrivateThreads: '建立私人話題',
    UseExternalStickers: '使用外部貼圖',
    SendMessagesInThreads: '於話題中傳送訊息',
    UseEmbeddedActivities: '使用活動',
    ModerateMembers: '禁言成員',
    ViewCreatorMonetizationAnalytics: '查看創作者收益分析',
    UseSoundboard: '使用音效板',
    UseExternalSounds: '使用外部聲音',
    SendVoiceMessages: '傳送語音訊息',
    SendPolls: '建立投票',
    CreateEvents: '建立活動',
    CreateGuildExpressions: '建立表達',
    UseExternalApps: '使用外部應用程式'
  }
}
